### PR TITLE
Add first pass of tests for EDB CLI

### LINKED ISSUE #304: EDB CLI are not currently tested
None of the functions in `commands.py` ([here](https://github.com/watertap-org/watertap/blob/main/watertap/edb/commands.py)) are currently unit tested. Is there a way to create unit tests for these command line functions?

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Changes proposed in this PR:
- Add tests for the EDB CLI

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by bknueven — APPROVED** [review]
These files were severely under-covered, so this should merged.

The diff coverage is clearly not an issue -- the project coverage goes up a whole percentage point with this PR.

**Review by aladshaw3 — APPROVED** [review]
LGTM

**Comment by aladshaw3** [comment]
@lbianchi-lbl Looks like we need to temporarily disable the check on `codecov/patch` or loosen up the coverage target for this case.

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl Looks like we need to temporarily disable the check on `codecov/patch` or loosen up the coverage target for this case. 

Since this should be a one-off corner case, I've just red-button merged it in.

**Pull request merged**
