### PR TITLE
Remove more unused imports

### LINKED ISSUE #994: Remove more unused imports
### Description

Using `flake8 --statistics --select=F401 --exclude=__init__.py .` gives 223 warnings about unused imports in watertap. I'll go through the package and remove these unused imports.

### Expected Behavior

Expect Python files to only import what is needed for the code in that file.

### Steps to Reproduce

Use the flake8 tool from within the watertap directory:

```
cd watertap
flake8 --statistics --select=F401 --exclude=__init__.py .
```

### Environment

- OS: macOS 12.6.3
- Python: 3.10
- WaterTAP: latest version

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by wigging**
## Fixes/Resolves:

Resolves issue #994.

## Summary/Motivation:

Remove unused imports throughout the watertap package. After this pull request is merged, the GitHub Actions should be updated to check future pull requests for unused imports.

## Changes proposed in this PR:
- Remove unused imports

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by wigging** [comment]
The `CONFIG_Template` that is imported in `watertap/core/membrane_channel0d.py` is unused in that file. However, if `CONFIG_Template` is removed then it breaks everything in watertap. It appears to be imported in the `membrane_channel0d.py` and then imported from that file into other files. `CONFIG_Template` is created in the `membrane_channel_base.py` so why isn't it imported from that file throughout the package?

**Comment by wigging** [comment]
The `ConcentrationPolarizationType` that is imported in `watertap/unit_models/reverse_osmosis_0D.py` is not used in that file. However, `ConcentrationPolarizationType` is imported from `watertap/unit_models/reverse_osmosis_0D.py` by other files. Why is this not imported from `watertap/core/membrane_channel_base.py` where it is originally defined?

**Comment by adam-a-a** [comment]
> `ConcentrationPolarizationType`
This was probably an oversight from when the RO 0D and 1D models were refactored with the new creation of the membrane_channel control volumes. I think you can alter the import to take straight from membrane_channel_base

**Comment by adam-a-a** [comment]
> The `ConcentrationPolarizationType` that is imported in `watertap/unit_models/reverse_osmosis_0D.py` is not used in that file. However, `ConcentrationPolarizationType` is imported from `watertap/unit_models/reverse_osmosis_0D.py` by other files. Why is this not imported from `watertap/core/membrane_channel_base.py` where it is originally defined?

@wigging This was probably an oversight from when the RO 0D and 1D models were refactored with the new creation of the membrane_channel control volumes. I think you can alter the import to take straight from membrane_channel_base

**Comment by bknueven** [comment]
> > The `ConcentrationPolarizationType` that is imported in `watertap/unit_models/reverse_osmosis_0D.py` is not used in that file. However, `ConcentrationPolarizationType` is imported from `watertap/unit_models/reverse_osmosis_0D.py` by other files. Why is this not imported from `watertap/core/membrane_channel_base.py` where it is originally defined?
> 
> @wigging This was probably an oversight from when the RO 0D and 1D models were refactored with the new creation of the membrane_channel control volumes. I think you can alter the import to take straight from membrane_channel_base

I would not be in favor of doing this -- I think the correct API has these things imported from the RO module. Users using the RO module don't need to know about `watertap.core.membrane_channel_base`.

**Comment by wigging** [comment]
@bknueven The `ConcentrationPolarizationType` is imported from `watertap.core` not from `watertap.core.membrane_channel_base`. It is defined in `watertap.core.membrane_channel_base` but it is imported from core because of how it's handled in `__init__.py`.

**Comment by adam-a-a** [comment]
Hmmm.. I see @bknueven 's point though. So in that case, it wasn't an oversight. For the user's sake, it would make more sense for a user to import `ConcentrationPolarizationType` from the RO unit (or at least have the option to).

**Comment by bknueven** [comment]
> Hmmm.. I see @bknueven 's point though. So in that case, it wasn't an oversight. For the user's sake, it would make more sense for a user to import `ConcentrationPolarizationType` from the RO unit (or at least have the option to).

Yes, the current behavior is intentional.

All the "option types" for the RO unit should be imported from a single location, IMHO.

**Comment by wigging** [comment]
@bknueven The enums `ConcentrationPolarizationType`, `MassTransferCoefficient`, `PressureChangeType`, and `FrictionFactor` are setup in watertap so they can be imported from `watertap.core`. It looks like this follows the IDAES approach where things like `MaterialBalanceType` and `FlowDirection` are imported from `idaes.core`.

**Comment by bknueven** [comment]
Let's do the following
1. Move `watertap/unit_models/reverse_osmosis_*.py` to new directory `watertap/unit_models/reverse_osmosis/`
2. Put the enums for reverse osmosis into `watertap/unit_models/reverse_osmosis/__init__.py` along side the unit model classes.

Then the API will be reasonably consistent between our various unit models. I would also be happy to leave the unused imports alone in these modules -- they do serve a specific purpose.

**Comment by wigging** [comment]
@bknueven I reverted the last two commits since the purpose of this pull request is to fix unused imports (not the API). To appease the linter and keep the original API, I added a few lines to the reverse osmosis unit models. See the latest commit. The use of the enum types and where they are located in the package should be handled better in watertap but I don't want to tackle that in this pull request.

**Review by adam-a-a — APPROVED** [review]
LGTM

**Comment by wigging** [comment]
@lbianchi-lbl Is anything else needed for this pull request?

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl Is anything else needed for this pull request?

Nope, thanks for bringing this over the finish line!

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
