### PR TITLE
ADM1 ASM2D translator block part 1

### PR DESCRIPTION
**Pull request by luohezhiming**
## Fixes/Resolves:

(replace this with the issue # fixed or resolved, if no issue exists then a brief statement of what this PR does)

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
Maybe you should change this to a draft PR rather than an open one.

**Comment by adam-a-a** [comment]
After speaking with @MarcusHolly and @luohezhiming , waiting on #948 for this to work

**Review by MarcusHolly — APPROVED** [review]
Just updated the documentation and made some minor changes, but everything LGTM. Any updates/revisions can be made in subsequent PRs.

**Review by agarciadiego — APPROVED** [review]

**Comment by ksbeattie** [comment]
I'm putting this on the June release board, since it looks like it is ready.

**Review by adam-a-a — APPROVED** [review]
LGTM- I modified the PR title so that the record can indicate that more work will likely be done on this (e.g., adding components)

**Pull request merged**
