### PR TITLE
Use README for long description

### LINKED ISSUE #1018: Fix description on PyPI
### Description

Watertap's webpage on PyPI has a single, unformatted, line for the description that requires the reader to scroll horizontally to read it. This is not a good user experience.

### Expected Behavior

A package's webpage on PyPI should be formatted and easy to read.

### Steps to Reproduce

See the webpage at https://pypi.org/project/watertap/ to view watertap's description on PyPI.

### Environment

The internet.

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by wigging**
## Fixes/Resolves:

This fixes issue #1018 regarding watertap's description that is displayed on PyPI at https://pypi.org/project/watertap/.

## Summary/Motivation:

The current description for watertap on PyPI is one long, unformatted, string. This pull request uses this repository's README content as the description that is displayed on PyPI.

## Changes proposed in this PR:
- Use README content for `long_description` in `setup.py`

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
@wigging Cool. I just have a quick Q- is there a way to see what the change looks like?

**Comment by wigging** [comment]
> Cool. I just have a quick Q- is there a way to see what the change looks like?

@adam-a-a I don't think you can preview how the description will look on PyPI. But it will look similar to how the README looks on GitHub.

**Comment by ksbeattie** [comment]
> > Cool. I just have a quick Q- is there a way to see what the change looks like?
> 
> @adam-a-a I don't think you can preview how the description will look on PyPI. But it will look similar to how the README looks on GitHub.

We might be able to push it to the test.pypi.org site, possibly directly from this branch as a dev or pre-release, and see what it looks like there.

**Review by adam-a-a — APPROVED** [review]
LGTM - my previous question was more out of curiosity, but I trust that this will be an improvement over what we currently have.

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
