### PR TITLE
Custom Model Demo Rework

### PR DESCRIPTION
**Pull request by MarcusHolly**
## Summary/Motivation:
Revamps the files previously living in the custom model demo folder to function as proper tutorials inside of Jupyter Notebook

## Changes proposed in this PR:
- Adds jupyter notebook tutorials for creating and using unit models and property models (4 files in total)
- Deletes the existing custom model demo folder

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
@lbianchi-lbl Do you know how I can resolve this notebook failure?

**Comment by lbianchi-lbl** [comment]
image

The kernelspec name should be changed to `watertap-dev` (the same as the existing notebooks). If the environment was set up according to [this how-to guide](https://watertap.readthedocs.io/en/stable/how_to_guides/notebooks.html#local-developer-installation), you should be able to do it directly from the Jupyter(Lab) interface.

**Comment by adam-a-a** [comment]
This is great, @MarcusHolly ! Good timing as we are aiming to spruce up tutorials and possibly use for upcoming workshops. I am thinking about whether we should bring in #1178 or this first. #1178 adds a landing page for all tutorials, and I repaired/renamed some tutorials that we have now. Maybe this one first, then I can add these new tutorials to the landing page. Thoughts @MarcusHolly @zacharybinger @ElmiraShamlou @kurbansitterley @luohezhiming ?

**Comment by MarcusHolly** [comment]
> This is great, @MarcusHolly ! Good timing as we are aiming to spruce up tutorials and possibly use for upcoming workshops. I am thinking about whether we should bring in #1178 or this first. #1178 adds a landing page for all tutorials, and I repaired/renamed some tutorials that we have now. Maybe this one first, then I can add these new tutorials to the landing page. Thoughts @MarcusHolly @zacharybinger @ElmiraShamlou @kurbansitterley @luohezhiming ?

@adam-a-a I agree - I think we can merge this one first and then update #1178

**Review by adam-a-a — APPROVED** [review]
Great! This is a priority as it may come in handy for upcoming workshop. I did not thoroughly check for typos, so if second reviewer could do that, that would be much appreciated.

**Review by savannahsakhai — APPROVED** [review]
LGTM. I did not see any typos.

**Pull request merged**
