### PR TITLE
Adding more infeasible utils and tests for new and existing infeasible utils

### PR DESCRIPTION
**Pull request by bknueven**
## Summary/Motivation:
Good to have more high-level `print_*` functions for ease-of-use.

## Changes proposed in this PR:
- add `print_infeasible_constraints` and `print_infeasible_bounds`
- add test for new and existing capability

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by adam-a-a — APPROVED** [review]
LGTM

**Review by andrewlee94 — COMMENTED** [review]
The code looks good, but we probably need to add some documentation for these functions (both full doc strings and content in the docs pages).

**Review by andrewlee94 — APPROVED** [review]
Mostly a rubber stamp, but look good to me.

**Comment by bknueven** [comment]
Since this is otherwise ready, I'll merge. I've opened an issue for the documentation, #317.

**Pull request merged**
