### PR TITLE
cyipopt-watertap

### PR DESCRIPTION
**Pull request by bknueven**
## Fixes/Resolves:
Add a WaterTAP wrapper for CyIpopt.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by avdudchenko — APPROVED** [review]
This looks good to me. So now to grab cyipopt we just do get_solver(solver='cyipopt-watertap')

**Comment by bknueven** [comment]
@lbianchi-lbl the uncovered lines are due to `cyipopt` not being in our test environment. Should I go ahead and add it, at least temporarily? In the medium term we'd resolve https://github.com/IDAES/idaes-ext/issues/261, which would necessitate installing cyipopt some other way.

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl the uncovered lines are due to `cyipopt` not being in our test environment. Should I go ahead and add it, at least temporarily? In the medium term we'd resolve [IDAES/idaes-ext#261](https://github.com/IDAES/idaes-ext/issues/261), which would necessitate installing cyipopt some other way.

Sure, although I think I don't have a good understanding of what is required to add it. Would it be similar to the way we use Ipopt from `conda-forge`? Or would we need to add a compilation step between `idaes get-extensions` and running the tests? Or something else entirely?

**Comment by bknueven** [comment]
> > @lbianchi-lbl the uncovered lines are due to `cyipopt` not being in our test environment. Should I go ahead and add it, at least temporarily? In the medium term we'd resolve [IDAES/idaes-ext#261](https://github.com/IDAES/idaes-ext/issues/261), which would necessitate installing cyipopt some other way.
> 
> Sure, although I think I don't have a good understanding of what is required to add it. Would it be similar to the way we use Ipopt from `conda-forge`? Or would we need to add a compilation step between `idaes get-extensions` and running the tests? Or something else entirely?

Yes -- the most straightforward way to get it is from `conda-forge` (https://anaconda.org/conda-forge/cyipopt). Leveraging the IDAES built of Ipopt is a longer-term goal.

**Comment by lbianchi-lbl** [comment]
> Yes -- the most straightforward way to get it is from `conda-forge` (https://anaconda.org/conda-forge/cyipopt). Leveraging the IDAES built of Ipopt is a longer-term goal.

OK, thanks for the clarification. It looks like we could add the `conda install -c conda-forge` command similarly to the one that installs Ray:

https://github.com/watertap-org/watertap/blob/aefad787f5753f35bc9414a7f5d6bb496e7cbb82/.github/workflows/checks.yml#L114-L116

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
