### PR TITLE
Update to all tests that involve chemistry after IDAES update

### PR DESCRIPTION
**Pull request by aladshaw3**
## Fixes/Addresses:

IDAES will be merging a PR soon that will disrupt all of our chemical models. This PR is being made to address those failures. 

NOTE: This PR is expected to fail until we start building against newest IDAES. 

## Summary/Motivation:

New IDAES PR will change how chemistry models are solved, thus we need to change all current tests to reflect that up coming change. 

## Changes proposed in this PR:
- All chemistry tests have to be changed (and all tests that use chemistry) 
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by aladshaw3** [comment]
NOTE: All tests here are expected to fail until watertap begins building against the latest update to IDAES main.

**Comment by lbianchi-lbl** [comment]
@aladshaw3 I've just pushed a commit to this PR's branch that updates the prerelease `idaes-pse` version requirements to the latest `watertap` tag on the `watertap-org/idaes-pse` fork as per #236. I see that the checks are currently failing, so feel free to revert the change and/or let me know if there's anything I can help with for this.

**Comment by aladshaw3** [comment]
@lbianchi-lbl The tests are all failing at the 'install dependencies' portion of the build. This error is beyond me, so someone else will need to have a look at it. 

It looks like the failures are in the "idaes get-extensions" command during the build (see below).


Output of "idaes get-extensions" command
  Traceback (most recent call last):
    File "/usr/share/miniconda/envs/watertap-dev/bin/idaes", line 5, in <module>
      from idaes.commands.base import command_base
    File "/usr/share/miniconda/envs/watertap-dev/lib/python3.6/site-packages/idaes/commands/__init__.py", line 28, in <module>
      loader.find_module(module_name).load_module(module_name)
    File "/usr/share/miniconda/envs/watertap-dev/lib/python3.6/site-packages/idaes/commands/env_info.py", line 19, in <module>
      from idaes.core.util.env_info import EnvironmentInfo
    File "/usr/share/miniconda/envs/watertap-dev/lib/python3.6/site-packages/idaes/core/__init__.py", line 15, in <module>
      from .unit_model import UnitModelBlockData, UnitModelBlock
    File "/usr/share/miniconda/envs/watertap-dev/lib/python3.6/site-packages/idaes/core/unit_model.py", line 24, in <module>
      from .property_base import StateBlock
    File "/usr/share/miniconda/envs/watertap-dev/lib/python3.6/site-packages/idaes/core/property_base.py", line 23, in <module>
      from pyomo.common.config import ConfigBlock, ConfigValue, In, Bool
  ImportError: cannot import name 'Bool'

**Comment by andrewlee94** [comment]
@lbianchi-lbl @aladshaw3 This error is occurring because the wrong version of Pyomo is being installed. It seems this PR is using a pre-release version of IDAES, which also requires a pre-release version of Pyomo, however I am guessing the last release version of Pyomo is being used instead.

**Comment by lbianchi-lbl** [comment]
@aladshaw3 @andrewlee94 I think you're both right, and thanks for spotting that. It looks we've reached the Second Circle of dependency hell (`idaes-pse` -> `pyomo`)... I've added the `[prerelease]` tag to the `idaes-pse` version specifier in `setup.py` and it now seems to be working.

**Review by lbianchi-lbl — APPROVED** [review]
Can't say much about the specific changes to the tests, but they now all work with the latest watertap-org/idaes-pse tag so this LGTM.

**Review by adam-a-a — APPROVED** [review]
Looks good to me. I won't be picky about commented code or anything like that since the purpose of this PR was to update tests to match the IDAES update on log concentrations.

**Pull request merged**
