### PR TITLE
Rename fsapi.FlowsheetExport dict() method and model_objects field to resolve Pydantic 2.0 warnings

### LINKED ISSUE #1344: Resolve Pydantic deprecation warnings
```txt

```txt
../../../../../opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151
  /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_objects" has conflict with protected namespace "model_".
  
  You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
    warnings.warn(
../../../../../opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydantic/main.py:1069: 210 warnings
ui/tests/test_flowsheet_interfaces.py: 10457 warnings
ui/tests/test_fsapi.py: 110 warnings
  /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydantic/main.py:1069: PydanticDeprecatedSince20: The `parse_obj` method is deprecated; use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
ui/tests/test_flowsheet_interfaces.py: 10520 warnings
ui/tests/test_fsapi.py: 96 warnings
  /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydantic/main.py:1024: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    warnings.warn('The `dict` method is deprecated; use `model_dump` instead.', category=PydanticDeprecatedSince20)
```

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Fixes/Resolves: #1344

(replace this with the issue # fixed or resolved, if no issue exists then a brief statement of what this PR does)

## Changes proposed in this PR:

- Replace calls to `.dict()` with `.model_dump()`
  - This is a straightforward change since it's just tracking changes in the Pydantic API
- Rename `model_objects` field to `exports` due to the `model_*` namespace being reserved by Pydantic
  - This could also be resolved by "unreserving" the `model_*` namespace
  - However, I think we should not do that if possible, otherwise it could be confusing for fields/methods where `model_` refers to completely different things coexisting in the same class
  - This is a more meaningful change, and the choice of alternative name should be discussed
  - I chose `exports` on the basis that the item class is named `ModelExport`
  - Everyone should feel free to come up with feedback and/or alternatives, but I think the choice should ultimately be up to @dangunter and @MichaelPesce
- Before merging this PR, we should thoroughly check whether the same changes should be applied to `watertap-org/watertap-ui` as well
### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by MichaelPesce — APPROVED** [review]
@lbianchi-lbl the changes look fine to me. We'll have to update the UI accordingly  - essentially just replace all references of `fs_exp.model_objects` with `fs_export.exports`. I've created a PR for that [here](https://github.com/watertap-org/watertap-ui/pull/114)

**Comment by dangunter** [comment]
I like the name "exports"

**Review by dangunter — APPROVED** [review]
This is good, thank you Ludovico for your help dealing with Pydantic.

**Comment by lbianchi-lbl** [comment]
> This is good, thank you Ludovico for your help dealing with Pydantic.

I think @MichaelPesce might have gotten the short end of the stick based on the sizes of the changes in watertap-org/watertap-ui#114 :sweat_smile:

**Pull request merged**
