### PR TITLE
Fix NF notebook and flowsheets for UI

### PR DESCRIPTION
**Pull request by adam-a-a**
## Fixes/Resolves:
#1072 
## Summary/Motivation:
Resolving NF flowsheet examples from NAWI spring meeting demo, which failed again after updating the repo for Pyomo/IDAES compatibility (#1049).

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
@lbianchi-lbl Unsure how to wipe my environment out from showing up as the kernel, which is unrecognized outside of my local machine (also not sure why it's showing up here in the first place):
image

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl Unsure how to wipe my environment out from showing up as the kernel, which is unrecognized outside of my local machine (also not sure why it's showing up here in the first place):
> image
> 

I see, sorry about the inconvenience, it is a bit annoying and we should find a better way to deal with this. You should be able to open the `.ipynb` file with a text editor (it's a JSON file, you might have to temporarily set the extension to `.json` to be able to do that), then search for `"kernel": ` and set it to the default which should be `"Python 3"`, then save and recommit.

I'm on mobile and I can't edit it from GitHub's interface at the moment; otherwise, I can do it when I'm back at my desk.

**Comment by adam-a-a** [comment]
> > @lbianchi-lbl Unsure how to wipe my environment out from showing up as the kernel, which is unrecognized outside of my local machine (also not sure why it's showing up here in the first place):
> > image
> 
> I see, sorry about the inconvenience, it is a bit annoying and we should find a better way to deal with this. You should be able to open the `.ipynb` file with a text editor (it's a JSON file, you might have to temporarily set the extension to `.json` to be able to do that), then search for `"kernel": ` and set it to the default which should be `"Python 3"`, then save and recommit.
> 
> I'm on mobile and I can't edit it from GitHub's interface at the moment; otherwise, I can do it when I'm back at my desk.

@lbianchi-lbl I wonder if we could do something like this: https://stackoverflow.com/questions/28908319/how-to-clear-jupyter-notebooks-output-in-all-cells-from-the-linux-terminal/58004619#58004619

I will try what you suggested. I am using VS Code now instead of Pycharm; the latter used to let me see the json format of the file, and usually I was able to clear all outputs/metadata. For some reason, the same doesn't seem to be true in VS Code, but I am probably missing something.

**Comment by adam-a-a** [comment]
@lbianchi-lbl I am getting failures on python versions 3.9 and 3.10 for win and linux, which might have something to do with numpy version: 
```

Exception raised:
    Traceback (most recent call last):
      File "C:\Miniconda\envs\watertap-dev\lib\doctest.py", line 1334, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest [scaling_factor][0]>", line 8, in <module>
        opt.solve(m)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\opt\base\solvers.py", line 597, in solve
        self._presolve(*args, **kwds)
      File "D:\a\watertap\watertap\watertap\core\plugins\solvers.py", line 106, in _presolve
        _, _, nlp = iscale.constraint_autoscale_large_jac(
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\idaes\core\util\scaling.py", line 695, in constraint_autoscale_large_jac
        nlp = PyomoNLP(m)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\interfaces\pyomo_nlp.py", line 108, in __init__
        super(PyomoNLP, self).__init__(nl_file)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\interfaces\ampl_nlp.py", line 56, in __init__
        self._asl = _asl.AmplInterface(self._nl_file)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\asl.py", line 272, in __init__
        AmplInterface.ASLib, AmplInterface.interface_version = _LoadASLInterface(
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\asl.py", line 32, in _LoadASLInterface
        array_1d_double = np.ctypeslib.ndpointer(
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\common\dependencies.py", line 75, in __getattr__
        raise DeferredImportError(self._moduleunavailable_message())
    pyomo.common.errors.DeferredImportError: The numpy module (an optional Pyomo dependency) failed to import: ModuleNotFoundError: No module named 'numpy._typing._ufunc'
Exception ignored in: <function AmplInterface.__del__ at 0x0000022955CEDDC0>
Traceback (most recent call last):
  File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\asl.py", line 312, in __del__
    self.ASLib.EXTERNAL_AmplInterface_free_memory(self._obj)
AttributeError: 'NoneType' object has no attribute 'EXTERNAL_AmplInterface_free_memory'
```
Oddly enough, the exceptions seem to occur due to the how-to documentation.

**Comment by adam-a-a** [comment]
@bknueven Xinhong fixed half of the problem here so this PR really just address the notebook.  However, there is a strange exception happening for python versions 3.9 and 3.10. It has something to do with a missing import for numpy (`numpy._typing._ufunc`)

**Comment by bknueven** [comment]
> @bknueven Xinhong fixed half of the problem here so this PR really just address the notebook. However, there is a strange exception happening for python versions 3.9 and 3.10. It has something to do with a missing import for numpy (`numpy._typing._ufunc`)

It looks like Python 3.9 is bringing in numpy 1.25.2 and Python 3.8 is bringing numpy 1.24.4.

What's a bit weird is this was happening before, so I'll need to see why it's popping up now..

**Comment by bknueven** [comment]
I diff'ed the packages against the most recent run on `main` for Python 3.9:
```
32c32
<   fonttools                     4.42.0
---
>   fonttools                     4.42.1
36c36
<   identify                      2.5.26
---
>   identify                      2.5.27
96c96
<   pymongo                       4.4.1
---
>   pymongo                       4.5.0
114,115c114,115
<   Sphinx                        6.2.1
<   sphinx-rtd-theme              1.2.2
---
>   Sphinx                        7.2.2
>   sphinx-rtd-theme              1.3.0
122c122
<   sphinxcontrib-serializinghtml 1.1.8
---
>   sphinxcontrib-serializinghtml 1.1.9
```

It looks like Sphinx changed on us ... that would at least explain why its the documentation code now failing..

**Comment by bknueven** [comment]
I'm re-running the check against `main` now: https://github.com/watertap-org/watertap/actions/runs/5912836890/job/16153623174

**Comment by adam-a-a** [comment]
@lbianchi-lbl @bknueven Should we change Sphinx dependency in setup.py to be limited 6.2.1 and earlier for now and have an issue for a better solution?

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl @bknueven Should we change Sphinx dependency in setup.py to be limited 6.2.1 and earlier for now and have an issue for a better solution?

I've just created #1109 to track this. In the meantime, feel free to try if fixing the Sphinx version helps (this is in `setup.py` under the `extras_require` tag named `dev`).

**Review by bknueven — APPROVED** [review]

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
