### PR TITLE
Remove idaes solver directives

### PR DESCRIPTION
**Pull request by bknueven**
## Summary/Motivation:
We're skipping several test which pass without an IDAES solver.

## Changes proposed in this PR:
- Remove `requires_idaes_solver` where not needed

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by hunterbarber — APPROVED** [review]
This revision is good.

**Comment by TimBartholomew** [comment]
I support this, what are the next steps to address the ion exchange test failures?

**Comment by bknueven** [comment]
> I support this, what are the next steps to address the ion exchange test failures?

Something changed between when I first opened this PR and when I merged in main 12 days ago. I've merged in main again to see if there's been a subsequent change in ion exchange (or anywhere else).

The easiest answer is "maintain the `requires_idaes_solver` directive on the failing tests". I'm not sure it's worth the effort to do more, though I generally think that a failure with the conda Ipopt is a sign of a potentially unstable model, at least in WaterTAP.

**Comment by kurbansitterley** [comment]
I am not sure what to do about the differences in solutions between Windows and Mac machines. Recall that part of the reason it took so long to merge in the IX model is because of this exact issue. The PR motivation is to remove idaes solver "where not needed". My view is that it is needed in this case.

**Comment by bknueven** [comment]
> I am not sure what to do about the differences in solutions between Windows and Mac machines. Recall that part of the reason it took so long to merge in the IX model is because of this exact issue. The PR motivation is to remove idaes solver "where not needed". My view is that it is needed in this case.

The difference is in the stricter initialization procedures we recently added. Before the unit was failing to initialize on macOS for one of the tests (and possibly on Linux/Windows too). We probably need to revisit the Ion Exchange initialization routine at some point.

That said, that's not what this PR is about, so I've just re-added the `requires_idaes_solver` directive in a few places.

**Review by andrewlee94 — APPROVED** [review]

**Pull request merged**
