### PR TITLE
Running black on everything

### PR DESCRIPTION
**Pull request by ksbeattie**
## Fixes/Addresses:

Reformatting all python code via `black`

## Summary/Motivation:

Standardize our coding style

## Changes proposed in this PR:
- Change all the files!
- replaces PR #281 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks good to me. Are we going to add a test to make sure the formatting remains consistent (or someway to autoformat each PR)?

**Comment by lbianchi-lbl** [comment]
@andrewlee94 that's a great point, thanks for bringing this up. I'll add a GHA check that will run Black in "check mode" and fail if it finds something to reformat.

**Comment by lbianchi-lbl** [comment]
@ksbeattie I've created https://github.com/ksbeattie/watertap/pull/1 with the GHA check (normally I'd be able to just push to the branch, but I think that our "equally absolutely powerful" permissions prevent that).

**Comment by bknueven** [comment]
I'm against merging this PR at this time. I've begun continuing to refactor the 0D/1D RO models on a branch (https://github.com/bknueven/watertap/tree/ro_refactor), and if this is merged I'll probably have either a painful rebase or I'll need to just start over. You can see the current diff here: https://github.com/watertap-org/watertap/compare/main...bknueven:ro_refactor?expand=1

**Comment by ksbeattie** [comment]
We're going to wait for @bknueven's PR to come in before this (or an equivalent "blackify") PR is merged in.

**Review by bknueven — CHANGES_REQUESTED** [review]
If we merge a PR like this, we should be sure to run against the new [stable release of black](https://github.com/psf/black/releases/tag/22.1.0), which critically for us changes black's [formatting of the power operator](https://github.com/psf/black/pull/2726).

**Comment by bknueven** [comment]
~~Waiting on #319.~~

**Comment by ksbeattie** [comment]
This is replaced by #478

**Pull request closed without merging**
