### PR TITLE
Minor MVC GUI Update

### PR DESCRIPTION
**Pull request by MarcusHolly**
## Changes proposed in this PR:
- Adds evaporator area as an input variable

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
@lbianchi-lbl Just wanted to make sure you're aware of this PR. If it's not too late to add this into the March release, that'd be great.

One minor issue is that I'm currently unable to run the GUI b/c the GUI requires a pydantic version between 2 and 3, but watertap 0.11.dev0 requires pydantic to be less than version 2. I assume this will be resolved when you make the new release?
image
image

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl Just wanted to make sure you're aware of this PR. If it's not too late to add this into the March release, that'd be great.
> 
> One minor issue is that I'm currently unable to run the GUI b/c the GUI requires a pydantic version between 2 and 3, but watertap 0.11.dev0 requires pydantic to be less than version 2. I assume this will be resolved when you make the new release? 

Thanks, the Pydantic 2 update was done in #1330, which has been merged in `main` as of 492e8db71acd8c469635c3fad9746904a38381b6, so reinstalling (uninstalling + reinstalling) WaterTAP, or installing in a fresh environment, should both work without warnings.

**Comment by MarcusHolly** [comment]
> > @lbianchi-lbl Just wanted to make sure you're aware of this PR. If it's not too late to add this into the March release, that'd be great.
> > One minor issue is that I'm currently unable to run the GUI b/c the GUI requires a pydantic version between 2 and 3, but watertap 0.11.dev0 requires pydantic to be less than version 2. I assume this will be resolved when you make the new release?
> 
> Thanks, the Pydantic 2 update was done in #1330, which has been merged in `main` as of [492e8db](https://github.com/watertap-org/watertap/commit/492e8db71acd8c469635c3fad9746904a38381b6), so reinstalling (uninstalling + reinstalling) WaterTAP, or installing in a fresh environment, should both work without warnings.

Maybe there's some intermediate step I'm missing, but I've tried `pip uninstall watertap` followed by `pip install watertap`, and I'm still seeing the pydantic requirement is not satisfied. So the GUI still fails to load... Maybe I just need to start a fresh environment.

image
image

**Comment by lbianchi-lbl** [comment]
@MarcusHolly OK, thanks. If this is an environment where `watertap-ui` is installed as well, that might be the reason for the errors, since watertap-org/watertap-ui#108 still needs to be merged (@MichaelPesce might be able to provide more details). You can check the currently installed versions of all packages by running `pip list` after activating the environment.

**Review by adam-a-a — APPROVED** [review]

**Review by luohezhiming — APPROVED** [review]
LGTM

**Pull request merged**
