### PR TITLE
Zero order costing package documentation

### PR DESCRIPTION
**Pull request by kurbansitterley**
## Summary/Motivation:

Creates zero order costing package doc

## Changes proposed in this PR:
- add zero order costing pkg rst file
- edit ``conf.py`` to left justify and slightly indent display of equations

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
Nice, @kurbansitterley ! It looks like you need to run black on the changed files but unsure about the readthedocs fail and whether the failure is tied to the black failure. Maybe run black and push again, then we can see what's going on.

**Comment by kurbansitterley** [comment]
> Nice, @kurbansitterley ! It looks like you need to run black on the changed files but unsure about the readthedocs fail and whether the failure is tied to the black failure. Maybe run black and push again, then we can see what's going on.

Yeah I went through the reinstalling my ``watertap-dev`` environment to include ``black``, but I pushed from my IDE so not sure if the ``pre-commit`` hooks work from there.

**Comment by adam-a-a** [comment]
@lbianchi-lbl we're seeing an error message for readthedocs and unsure where the issue is exactly. Would you happen to have come across this before?

**Comment by adam-a-a** [comment]
> @lbianchi-lbl we're seeing an error message for readthedocs and unsure where the issue is exactly. Would you happen to have come across this before?

@lbianchi-lbl Nevermind! We were just missing a section title before the autoclass directive! With that added in, the readthedocs check is passing!

**Review by bknueven — APPROVED** [review]

**Comment by bknueven** [comment]
At some point, we should reference the IDAES documentation on flowsheet and unit costing in this document. But after a cursory search it seems like such documentation has not yet been created.

**Review by adam-a-a — APPROVED** [review]
LGTM - @kurbansitterley were there things you still wanted to add at this point, or can we take this out of draft mode and merge?

**Pull request merged**
