### PR TITLE
Metab GUI connection

### PR DESCRIPTION
**Pull request by TimBartholomew**
## Fixes/Resolves:

(replace this with the issue # fixed or resolved, if no issue exists then a brief statement of what this PR does)

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
@TimBartholomew I pushed a couple of changes, one where you put the cost expressions under the flowsheet instead of flowsheet.costing and then a bug in the API where it didn't get the value of expressions properly from Pyomo. Once I did that it seems to work

**Comment by TimBartholomew** [comment]
Ah yep thanks. I'll keep adding more... there's a lot more :)

**Comment by TimBartholomew** [comment]
@dangunter @MichaelPesce, I added all the inputs. I still need to add all the outputs (I just have the original small set) but I have meetings the rest of the day.

I don't know how to run the code, so there might be some small mistakes again

**Comment by MichaelPesce** [comment]
@TimBartholomew current set of inputs and outputs look fine on the UI end

**Comment by dangunter** [comment]
@dangunter Look at this error and find offending variable

**Review by dangunter — APPROVED** [review]
Looks good

**Review by MichaelPesce — APPROVED** [review]

**Pull request merged**
