### PR TITLE
fix the two tests that were skipped

### PR DESCRIPTION
**Pull request by adam-a-a**
## Fixes/Resolves:
Resolves issue identified in PR #699  
## Summary/Motivation:
Fix tests in ion prop package

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
@lbibl Upon further review of the assert_electroneutrality method, I think that the stateblock was indeed solving. Happy to discuss with you to ensure there is no error within the method.

**Comment by lbibl** [comment]
@adam-a-a : after our discussion accurately located the issue, I think I came up an easy solution to fix it, which is a "double solve" of the model in the `assert_neutrality` function and the first solve is equivalent to an `initialize`.  By this mean the model was solved at higher precision and can pass the common 1e-8 tol.  Please see if this looks good to you.

**Review by lbibl — APPROVED** [review]

**Review by srikanthallu — COMMENTED** [review]
@adam-a-a , do you know why there are two tests that xfail ? Are we marking this anywhere ?

**Comment by lbibl** [comment]
> @adam-a-a , do you know why there are two tests that xfail ? Are we marking this anywhere ?

I think that (xfails) is only associated with an experimental MacOS and should not cause concerns.  @bknueven might know more about this.

**Comment by bknueven** [comment]
> > @adam-a-a , do you know why there are two tests that xfail ? Are we marking this anywhere ?
> 
> I think that (xfails) is only associated with an experimental MacOS and should not cause concerns. @bknueven might know more about this.

If you're seeing this on macOS its because these tests did not pass using Ipopt with MuMPS at some point. We should probably try removing the `@pytest.mark.requires_idaes_solver` to make sure they're really still necessary.

**Comment by bknueven** [comment]
Ideally we'd also refactor this test (probably in a separate PR) to avoid such issues in the future.

**Review by bknueven — APPROVED** [review]

**Pull request merged**
