### PR TITLE
Ion exchange 0D single component model

### PR DESCRIPTION
**Pull request by kurbansitterley**
## Fixes/Resolves:

Replace PR #559 

## Summary/Motivation:

Replace PR #559 

## Changes proposed in this PR:
- Single component Ion exchange 0D model
- test file tested on Windows machine
- Add IX costing method

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by TimBartholomew** [comment]
@lbibl in some of these tests, electrodialysis model tests are failing, but the files changed shouldn't be impacting them. So it seems that the ED model tests are not stable.

@bknueven in some of these tests, LSRRO multisweep test are failing, but the files changed shouldn't be impacting them. So it seems that that test is not stable.

Kurby is going to try to move the costing parameters and variables, which are the only thing that could be impacting those flowsheets.

**Comment by bknueven** [comment]
> @bknueven in some of these tests, LSRRO multisweep test are failing, but the files changed shouldn't be impacting them. So it seems that that test is not stable.

For the LSRRO models, we made this decision to test the "4 corners" of the search space we explored. However, in retrospect I think that is a mistake, because it leads to somewhat ill-posed problems. E.g., optimizing a 4- or 5-stage LSRRO flowsheet against a low feed concentration leads to a problem with lots of local minima. We should probably be using test values that make operational sense. @adam-a-a thoughts? I'm opening an issue for this -- we also experienced this after making a different change -- the LSRRO flowsheet solved to a different local minima in one or more cases.

**Comment by lbibl** [comment]
I can recognize the ED flowsheet (not the unit model) failure in certain OS the same one I tackled in the last PR.   I believe it is also caused by local minima of the problem itself.  My previous solution was only to tailor the scaling to let all platforms land on the same minimum.   The optimization problem in ED flowsheet tested at this stage is more arbitrary than carefully-designed, so I expect a better problem design to update the current version as a permanent solution.  For now,  I think we can 1) find out why the changes in the costing package caused the effect and change there, 2) tailor the scaling again as a temporary solution, or 3) disable the optimization test in the ED flowsheet temporarily.

**Comment by lbibl** [comment]
I saw the updated costing package added 18 variables and 2 constraints to the optimization problem in the ED flowsheet, where the obj is LCOW.  I am not yet that familiar with the costing package.  Can someone tell if this is reasonable?

**Comment by lbibl** [comment]
> I saw the updated costing package added 18 variables and 2 constraints to the optimization problem in the ED flowsheet, where the obj is LCOW. I am not yet that familiar with the costing package. Can someone tell if this is reasonable?

It seems Issue #676  is related to my question.

**Comment by kurbansitterley** [comment]
> I saw the updated costing package added 18 variables and 2 constraints to the optimization problem in the ED flowsheet, where the obj is LCOW. I am not yet that familiar with the costing package. Can someone tell if this is reasonable?

IX costing added 18 variables so that tracks. Not totally sure where the two constraints could come from, but I did add two `defined_flows`.

**Comment by bknueven** [comment]
> Kurby is going to try to move the costing parameters and variables, which are the only thing that could be impacting those flowsheets.

@TimBartholomew I think this is unnecessary with IDAES/idaes-pse#938, and it would be better to make such changes as part of #676.

**Comment by lbibl** [comment]
PR #696 , once merged, is expected to resolve the error in the /flowsheet/electrodialysis/tests/test_electrodialysis_1stack.py.

**Review by adam-a-a — APPROVED** [review]
LGTM - I think any further modification can be handled in a subsequent PR, aside from getting the tests to pass, which I am assuming will end up being simple fixes.

**Review by bknueven — COMMENTED** [review]
@kurbansitterley I know we want to merge this yesterday -- but any chance we could get a simple test for the costing code?

We've been including that with the unit model tests for ease with other units.

**Review by bknueven — APPROVED** [review]

**Pull request merged**
