### PR TITLE
Adding density parameter to MCAS when `DensityCalculation.constant`

### PR DESCRIPTION
**Pull request by hunterbarber**
## Fixes/Resolves:
DensityCalculation.constant allowed for solution density to be constant, but only at 1000 kg/m3. Adding a parameter to allow the constant density to be manipulated from 1000.

## Changes proposed in this PR:
- add dens_mass_const as param

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by adam-a-a — APPROVED** [review]
LGTM

**Review by MarcusHolly — APPROVED** [review]
LGTM

**Comment by adam-a-a** [comment]
@hunterbarber - just realized one small addition here- can you modify the documentation to reflect this change?

**Review by adam-a-a — CHANGES_REQUESTED** [review]
I know I approved initially, but I realized we should include this modification in the documentation now rather than pushing it off, especially since it's a small change.

**Comment by hunterbarber** [comment]
> I know I approved initially, but I realized we should include this modification in the documentation now rather than pushing it off, especially since it's a small change.

From what I've seen Params() typically aren't reflected in the documentation at all, let me double check and get back to you.

**Comment by hunterbarber** [comment]
@adam-a-a Other than this being captured by the class automation I don't see any misinformation in the docs, or any mention of the old method. The only thing I did see when actually working on the other changes was that `dens_mass_w_phase` is in the docs but not in the actual code but should be `dens_mass_solvent`(?), but that's a different conversation.

**Comment by hunterbarber** [comment]
> @adam-a-a Other than this being captured by the class automation I don't see any misinformation in the docs, or any mention of the old method. The only thing I did see when actually working on the other changes was that `dens_mass_w_phase` is in the docs but not in the actual code but should be `dens_mass_solvent`(?), but that's a different conversation.

image

**Comment by hunterbarber** [comment]
> @adam-a-a Other than this being captured by the class automation I don't see any misinformation in the docs, or any mention of the old method. The only thing I did see when actually working on the other changes was that `dens_mass_w_phase` is in the docs but not in the actual code but should be `dens_mass_solvent`(?), but that's a different conversation.

Also that .lalibert actually isn't currently supported.

**Comment by adam-a-a** [comment]
@hunterbarber I hadn't thoroughly looked at the current state of the MCAS documentation. Originally, we didn't have any documentation for it and wanted to spin something out quickly. Looking at it now though, its order deviates from other documentation (e.g., class documentation usually goes at the end), and it looks like it could use a fair amount of improvement. That should be reserved for another PR though. Can you make an issue with a running to-do list for improving the MCAS documentation (or add to the to-do list if an issue already exists for it)?

**Comment by hunterbarber** [comment]
> @hunterbarber I hadn't thoroughly looked at the current state of the MCAS documentation. Originally, we didn't have any documentation for it and wanted to spin something out quickly. Looking at it now though, its order deviates from other documentation (e.g., class documentation usually goes at the end), and it looks like it could use a fair amount of improvement. That should be reserved for another PR though. Can you make an issue with a running to-do list for improving the MCAS documentation (or add to the to-do list if an issue already exists for it)?

It's up in #905, please add anything else you may have caught.

**Review by adam-a-a — APPROVED** [review]
LGTM

**Pull request merged**
