### PR TITLE
Minor ADM1 Refinement

### PR DESCRIPTION
**Pull request by MarcusHolly**
## Fixes/Resolves:

Issue #909 

## Changes proposed in this PR:
- Removes unnecessary imports
- Adds class documentation for the property package and unit model

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by agarciadiego — APPROVED** [review]
LGTM

**Review by luohezhiming — APPROVED** [review]
LGTM

**Review by adam-a-a — CHANGES_REQUESTED** [review]
LGTM- except if we're checking off that task in issue #909 , we should also be adding the class documentation to the anaerobic_digestor.rst file.

**Comment by MarcusHolly** [comment]
> LGTM- except if we're checking off that task in issue #909 , we should also be adding the class documentation to the anaerobic_digestor.rst file.

@adam-a-a I've added the class documentation to the anaerobic digestor file, so this should be good to merge now.

**Review by adam-a-a — APPROVED** [review]
LGTM

**Pull request merged**
