### PR TITLE
move case studies

### PR DESCRIPTION
**Pull request by TimBartholomew**
## Fixes/Addresses:
None

## Summary/Motivation:
Moves case studies to flowsheets - this deemphasizes the case studies in that users will see the more vetted flowsheet examples before opening the case studies.

## Changes proposed in this PR:
- moved the case study director to a subdirectory in examples/flowsheets

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by adam-a-a — DISMISSED** [review]
LGTM

**Comment by adam-a-a** [comment]
@TimBartholomew readthedocs check is failing because of one warning:
```
WARNING: autodoc: failed to import module 'case_studies' from module 'watertap.examples'; the following exception was raised:
No module named 'watertap.examples.case_studies'
```

**Review by luohezhiming — DISMISSED** [review]
LGTM

**Review by adam-a-a — APPROVED** [review]

**Review by tarnold17 — APPROVED** [review]
LGTM

**Pull request merged**
