### PR TITLE
WT3 bioreactor

### PR DESCRIPTION
**Pull request by TimBartholomew**
## Summary/Motivation:
Adds zero order bioreactor, which has selenium and boron removal

## Changes proposed in this PR:
- Added unit and tests

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by TimBartholomew** [comment]
While creating a basic unit is really fast, creating the test takes some time, I would think that a test harness would be pretty valuable.

Also note that I combined the default removal fraction test with the original, rather than having two separate tests. I'm not sure what the value is of not including a component that needs the default value originally.

**Comment by adam-a-a** [comment]
> Also note that I combined the default removal fraction test with the original, rather than having two separate tests. I'm not sure what the value is of not including a component that needs the default value originally.

I think you're right about this. Originally, we based our tests on @andrewlee94 's first unit (nanofiltration) where he was testing functionality between inclusion/exclusion of default removal in early stages. However, we could probably save effort by only adding the test _with_ default removal. 

With that said, we might want to add the other test for checking subtypes although this unit doesn't have any yet. When/if we do add subtypes, that test would cover new additions. You can choose to add that in now or save it for when subtypes are added later.

**Comment by adam-a-a** [comment]
Also, we might think about modeling this as a sido_r model for the AMO effort, but siso works for the WT3 implementation.

**Comment by bknueven** [comment]
> While creating a basic unit is really fast, creating the test takes some time, I would think that a test harness would be pretty valuable.


This seems likely, but I would recommend any such code just reflect the current structure of these models. E.g., maybe there's a test function you call for the `build_siso` function or the `constant_intensity` function. Similarly for the basic database functionality.

So in my mind this looks quite different from the test harnesses we've used in the past and reflects the structure of the basic models. Non-basic models would have additional test code to  reflect the additional variables and constraints.

**Comment by adam-a-a** [comment]
> > While creating a basic unit is really fast, creating the test takes some time, I would think that a test harness would be pretty valuable.
> 
> This seems likely, but I would recommend any such code just reflect the current structure of these models. E.g., maybe there's a test function you call for the `build_siso` function or the `constant_intensity` function. Similarly for the basic database functionality.
> 
> So in my mind this looks quite different from the test harnesses we've used in the past and reflects the structure of the basic models. Non-basic models would have additional test code to reflect the additional variables and constraints.

To add to that, I think the tests are easy enough to copy/paste/revise to fast-track model migration. A test harness approach would be a nice-to-have, but I think our time would be better spent on directly migrating models and pasting/revising tests.

**Review by adam-a-a — APPROVED** [review]
LGTM - we might modify this later or make a new bioreactor unit for AMO needs, but this is sufficient for WT3 migration.

**Review by bknueven — APPROVED** [review]

**Pull request merged**
