### PR TITLE
Allow the parameter sweep to accept pre-sampled values

### PR DESCRIPTION
**Pull request by k1nshuk**
## Fixes/Resolves:

Fixes the inability of the parameter sweep tool to accept pre-sampled values from a separate experiment.

## Summary/Motivation:

Enables better analysis and validation for existing flowsheet configurations

## Changes proposed in this PR:
- Creation of a predetermined random sampling type
- Creation of a predetermined fixed sampling type

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by avdudchenko — APPROVED** [review]
This looks good, but can we add documentation note on how user to specify these values? from raw code its not quiet clear.

**Comment by adam-a-a** [comment]
@avdudchenko This arose from a need to provide a preset list of values that a user might want to run. Say I want to sweep across the following concentrations (for whatever reason): [0.9, 2.3, 3.98]. I can't do that with the existing functionality. @k1nshuk modified this so that we can essentially just provide a list of values that we want to sweep across. 

Taking my arbitrary example, my interpretation of @k1nshuk 's implementation is that I'd essentially do the following to setup my sweep:
```
param_dict = dict()
param_dict["concentration"] = PredeterminedFixedSample(m.fs.feed.properties[0].conc_mass_phase_comp["Liq", "NaCl"], [0.9, 2.3, 3.98])
```

**Comment by adam-a-a** [comment]
> @avdudchenko This arose from a need to provide a preset list of values that a user might want to run. Say I want to sweep across the following concentrations (for whatever reason): [0.9, 2.3, 3.98]. I can't do that with the existing functionality. @k1nshuk modified this so that we can essentially just provide a list of values that we want to sweep across.
> 
> Taking my arbitrary example, my interpretation of @k1nshuk 's implementation is that I'd essentially do the following to setup my sweep:
> 
> ```
> param_dict = dict()
> param_dict["concentration"] = PredeterminedFixedSample(m.fs.feed.properties[0].conc_mass_phase_comp["Liq", "NaCl"], [0.9, 2.3, 3.98])
> ```

That said, we can probably follow this up with some quick documentation in one of the how-to documents.

**Comment by adam-a-a** [comment]
@k1nshuk Not too sure why the MPI tests are failing. Most PRs I deal with don't ever deal with MPI.  Any thoughts?

**Comment by k1nshuk** [comment]
@adam-a-a I think I fixed the tests. Waiting for the CI tests to complete. Also added some documentation and docstrings.

**Review by adam-a-a — CHANGES_REQUESTED** [review]
LGTM, but holding off on approving/merging until @k1nshuk rules out a potential MPI bug.

**Comment by k1nshuk** [comment]
@adam-a-a @avdudchenko Okay, it should be good to merge now.

**Review by adam-a-a — APPROVED** [review]
LGTM

**Pull request merged**
