### PR TITLE
BSM2 GUI Update

### PR DESCRIPTION
**Pull request by MarcusHolly**
## Fixes/Resolves:

Issue #1153 

## Changes proposed in this PR:
- Adds output boxes for all key streams

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
GUI screenshots (sorry for the low resolution)

Input Tab:
image

Output Tab:
image

image

**Comment by adam-a-a** [comment]
@MarcusHolly This is good. I think we should replace "ASM1/ADM1 Translator Outlet" with "Anaerobic Digestor Inlet". We should also replace "ADM1/ASM1 Translator Inlet" with "Anaerobic Digestor Liquid Outlet". My thought is that doing so would make these outputs more apparent, and I think users would generally be seeking out calculations tied to the anaerobic digestor's inlet/outlet conditions, and labeling as such makes it more obvious.

Do you agree, and is there any reason anyone thinks we should not do this? @MarcusHolly @luohezhiming @agarciadiego

**Comment by MarcusHolly** [comment]
> @MarcusHolly This is good. I think we should replace "ASM1/ADM1 Translator Outlet" with "Anaerobic Digestor Inlet". We should also replace "ADM1/ASM1 Translator Inlet" with "Anaerobic Digestor Liquid Outlet". My thought is that doing so would make these outputs more apparent, and I think users would generally be seeking out calculations tied to the anaerobic digestor's inlet/outlet conditions, and labeling as such makes it more obvious.
> 
> Do you agree, and is there any reason anyone thinks we should not do this? @MarcusHolly @luohezhiming @agarciadiego

Sounds good. My thought process was that it'd be more apparent for the user to know what the translator was doing if they could easily see what streams corresponded to the inlets and outlets for the translators. But with your change, they can still decipher that pretty easily if they just look at the flowsheet image. And I agree that users would prob want to see the AD inlet and outlets directly listed rather than having them "hidden" as translator block streams.

**Comment by agarciadiego** [comment]
> > @MarcusHolly This is good. I think we should replace "ASM1/ADM1 Translator Outlet" with "Anaerobic Digestor Inlet". We should also replace "ADM1/ASM1 Translator Inlet" with "Anaerobic Digestor Liquid Outlet". My thought is that doing so would make these outputs more apparent, and I think users would generally be seeking out calculations tied to the anaerobic digestor's inlet/outlet conditions, and labeling as such makes it more obvious.
> > Do you agree, and is there any reason anyone thinks we should not do this? @MarcusHolly @luohezhiming @agarciadiego
> 
> Sounds good. My thought process was that it'd be more apparent for the user to know what the translator was doing if they could easily see what streams corresponded to the inlets and outlets for the translators. But with your change, they can still decipher that pretty easily if they just look at the flowsheet image. And I agree that users would prob want to see the AD inlet and outlets directly listed rather than having them "hidden" as translator block streams.

I've seen sources that give it a name like "Anaerobic Digestor Inlet" and add in parenthesis if it is pre/post interface, i.e., "Anaerobic Digestor Inlet (post interface)"

**Comment by agarciadiego** [comment]
> > > @MarcusHolly This is good. I think we should replace "ASM1/ADM1 Translator Outlet" with "Anaerobic Digestor Inlet". We should also replace "ADM1/ASM1 Translator Inlet" with "Anaerobic Digestor Liquid Outlet". My thought is that doing so would make these outputs more apparent, and I think users would generally be seeking out calculations tied to the anaerobic digestor's inlet/outlet conditions, and labeling as such makes it more obvious.
> > > Do you agree, and is there any reason anyone thinks we should not do this? @MarcusHolly @luohezhiming @agarciadiego
> > 
> > 
> > Sounds good. My thought process was that it'd be more apparent for the user to know what the translator was doing if they could easily see what streams corresponded to the inlets and outlets for the translators. But with your change, they can still decipher that pretty easily if they just look at the flowsheet image. And I agree that users would prob want to see the AD inlet and outlets directly listed rather than having them "hidden" as translator block streams.
> 
> I've seen sources that give it a name like "Anaerobic Digestor Inlet" and add in parenthesis if it is pre/post interface, i.e., "Anaerobic Digestor Inlet (post interface)"

This gets to your point @adam-a-a and gives information to the user about the components

**Comment by MarcusHolly** [comment]
> > > > @MarcusHolly This is good. I think we should replace "ASM1/ADM1 Translator Outlet" with "Anaerobic Digestor Inlet". We should also replace "ADM1/ASM1 Translator Inlet" with "Anaerobic Digestor Liquid Outlet". My thought is that doing so would make these outputs more apparent, and I think users would generally be seeking out calculations tied to the anaerobic digestor's inlet/outlet conditions, and labeling as such makes it more obvious.
> > > > Do you agree, and is there any reason anyone thinks we should not do this? @MarcusHolly @luohezhiming @agarciadiego
> > > 
> > > 
> > > Sounds good. My thought process was that it'd be more apparent for the user to know what the translator was doing if they could easily see what streams corresponded to the inlets and outlets for the translators. But with your change, they can still decipher that pretty easily if they just look at the flowsheet image. And I agree that users would prob want to see the AD inlet and outlets directly listed rather than having them "hidden" as translator block streams.
> > 
> > 
> > I've seen sources that give it a name like "Anaerobic Digestor Inlet" and add in parenthesis if it is pre/post interface, i.e., "Anaerobic Digestor Inlet (post interface)"
> 
> This gets to your point @adam-a-a and gives information to the user about the components

I've added the pre & post-interface in parentheses like Alejandro suggested.
image

**Review by agarciadiego — APPROVED** [review]
LGTM

**Comment by adam-a-a** [comment]
Great, this is exactly the kind of feedback I was looking for! One subtle point @MarcusHolly --we use "interface" and "translator". Perhaps we should stick with one for consistency (at least in the GUI), and I think it should be "interface".

**Review by luohezhiming — APPROVED** [review]

**Review by adam-a-a — APPROVED** [review]
LGTM

**Pull request merged**
