### PR TITLE
Update idaes-pse requirement for current dev version to latest tag on watertap-org fork

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary/Motivation:

- Set the idaes-pse requirement to the current `main` of IDAES/idaes-pse, which incorporated the fixes that should address most of the issues in #287
- @andrewlee94 will address 2 of the remaining test failures, which should leave only one expected test failure to be fixed on the WaterTAP side

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by bknueven** [comment]
@lbianchi-lbl the new tag points to the same IDAES commit as the old tag: https://github.com/watertap-org/idaes-pse/commit/2021d131f3bf4f8ef50ba325089560f5bcc18469.

**Review by aladshaw3 — APPROVED** [review]
There are no issues/failures currently, so I am gonna approve this. Not sure what the expected errors were, but they didn't occur, so it may have been fixed with some of the recent PRs that got merged earlier today.

**Comment by lbianchi-lbl** [comment]
@bknueven You're absolutely right, thanks for catching that. I must have done the tag creation and pull in the wrong order. I'll recreate the tag and re-run the tests again.

**Comment by aladshaw3** [comment]
Revoking my approval due to a test failure after updated tag. 

@adam-a-a @TimBartholomew The failure is in the NaCl  and Seawater prop packages. 

So far, none of the chem tests have failed that I can see.

**Review by aladshaw3 — CHANGES_REQUESTED** [review]
NaCl and Seawater Prop Packages are failing

===========================
FAILED watertap/property_models/tests/test_NaCl_prop_pack.py::TestNaClProperty_idaes::test_initialize_failure
FAILED watertap/property_models/tests/test_seawater_prop_pack.py::TestSeawaterProperty_idaes::test_initialize_failure

**Comment by AndrewLee** [comment]
wrong Andrew Lee

**Comment by andrewlee94** [comment]
The failures in the NaCl and seawater property package are the ones I was expecting to see - I will fix these today,

**Review by bknueven — APPROVED** [review]

**Review by andrewlee94 — APPROVED** [review]

**Comment by lbianchi-lbl** [comment]
@aladshaw3 this should auto-merge as soon as the requested changes in your review are marked as addressed:

image

**Review by aladshaw3 — APPROVED** [review]

**Pull request merged**
