### PR TITLE
Add therm_cond_phase and visc_d_phase to water_prop_pack

### PR DESCRIPTION
**Pull request by savannahsakhai**
## Summary/Motivation:

Adds necessary properties (thermal conductivity and dynamic viscosity) needed for membrane distillation

## Changes proposed in this PR:
- adds therm_cond_phase
- adds visc_d_phase 
- updates test file

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by adam-a-a — APPROVED** [review]
LGTM - nice job!

**Comment by adam-a-a** [comment]
One thing came to mind- we should also update the technical reference for the water prop pack to reflect these additions. Can do it in this PR or a follow-on.

**Comment by savannahsakhai** [comment]
> One thing came to mind- we should also update the technical reference for the water prop pack to reflect these additions. Can do it in this PR or a follow-on.

I went ahead and added the documentation update.

**Review by ElmiraShamlou — APPROVED** [review]
LGTM

**Pull request merged**
