### PR TITLE
Making place to live for pfas treatment analysis

### PR DESCRIPTION
**Pull request by adam-a-a**
## Fixes/Resolves:

(replace this with the issue # fixed or resolved, if no issue exists then a brief statement of what this PR does)

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by hunterbarber** [comment]
@kurbansitterley I'm just noting that I'm fine with this location. When you see and approve of this go ahead and merge and we'll start working out of here.

**Comment by adam-a-a** [comment]
@hunterbarber I meant to leave this up as an example to show you guys. We don't need to wait for this particular one (but maybe for more complicated changes that we want to highlight within the group)

**Comment by hunterbarber** [comment]
I knew that, I just wanted to make sure Kurby made a note of the file path just in case he would have found himself searching through folders. All good!

**Comment by kurbansitterley** [comment]
Thank you guys and sorry for the tardiness!

**Pull request merged**
