### PR TITLE
Move get_solver test to more natural location

### PR DESCRIPTION
**Pull request by bknueven**
## Summary/Motivation:
In anticipation of moving ipopt-watertap and associated code to its own repository.

## Changes proposed in this PR:
- move test for `watertap.core.solvers.get_solver` into `watertap.core.tests.test_solvers`

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
- This is related to #1511
- We might want to wait until we have a clearer idea of what the final module/import structure should look like before merging this
- OTOH the changes should not have external impact and therefore could be merged in now

**Comment by bknueven** [comment]
> * This is related to [Extract WaterTAP solvers to separately installable package #1511](https://github.com/watertap-org/watertap/issues/1511)
> 
> * We might want to wait until we have a clearer idea of what the final module/import structure should look like before merging this
> 
> * OTOH the changes should not have external impact and therefore could be merged in now

I went ahead an opened this PR because it seemed like a more natural organization of the existing tests, regardless of the outcome of #1511.

The current organization is a historical accident dating back to when WaterTAP was using the IDAES `get_solver` function, and probably should have been part of #1353.

**Review by lbianchi-lbl — APPROVED** [review]
Sounds good, thanks for the clarification @bknueven

**Review by ksbeattie — APPROVED** [review]
LGTM

**Review by adam-a-a — APPROVED** [review]

**Pull request merged**
