### PR TITLE
Add GUI for RO flowsheet

### PR DESCRIPTION
**Pull request by luohezhiming**
## Summary/Motivation:
Add GUI for the `RO_with_energy_recovery.py` flowsheet

## Changes proposed in this PR:
- add GUI
- add figure

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
Screenshots of GUI

Input Tab:
image

Output Tab: 
image

**Comment by MarcusHolly** [comment]
I'll let other people comment on whether or not more things should be included in the input and output tabs, but I think every variable in the input tab should start off as "fixed". There are some that have been changed to "free", which I assume you just did to make sure the sweep was working correctly.

My new PR (#1160) is also running into pylint errors... @lbianchi-lbl is it ok if we bypass this test or should we really aim to resolve it? These are my remaining pylint warnings, and I don't think resolving any of these would be trivial (with the exception of the import warnings potentially). I'm also not convinced that these pylint errors are related to the GUI files we're modifying.
image

**Comment by adam-a-a** [comment]
> I'll let other people comment on whether or not more things should be included in the input and output tabs, but I think every variable in the input tab should start off as "fixed". There are some that have been changed to "free", which I assume you just did to make sure the sweep was working correctly.
> 
> My new PR (#1160) is also running into pylint errors... @lbianchi-lbl is it ok if we bypass this test or should we really aim to resolve it? These are my remaining pylint warnings, and I don't think resolving any of these would be trivial (with the exception of the import warnings potentially). I'm also not convinced that these pylint errors are related to the GUI files we're modifying. image

This pylint issue popped up in at least PR #1145, which @bknueven temporarily resolved by limiting the version of pylint in PR #1145. That one will be merged very soon.

**Comment by luohezhiming** [comment]
> Screenshots of GUI
> 
> Input Tab: image
> 
> Output Tab: image

Thanks, Marcus. This is pretty good point, one of the problem is the feed flowrate and concentration are calculated by `calculate_state` and not directly specified. That's why it is shown as free variables in the GUI. I've already modified the inputs of feed as flowrate of water and NaCl. Right now, they are all fixed variables that we can make sweep analysis

**Comment by adam-a-a** [comment]
@luohezhiming I think this should be good to merge once you update the flowsheet image to represent the configuration (i.e., include pumps and ERD)

**Comment by luohezhiming** [comment]
> @luohezhiming I think this should be good to merge once you update the flowsheet image to represent the configuration (i.e., include pumps and ERD)

@adam-a-a I updated the figure and I think it is ready for merge, we can upgrade it with different types once the UI option is available.

**Review by MarcusHolly — APPROVED** [review]

**Comment by adam-a-a** [comment]
@MichaelPesce @dangunter btw- just a reminder that this is one of the examples that we think would serve well for testing config options (e.g., switch between one flowsheet build and another)

**Review by adam-a-a — APPROVED** [review]
LGTM

**Pull request merged**
