### PR TITLE
Address Sphinx failures

### LINKED ISSUE #1109: Errors when building Sphinx docs related to AmplInterface and/or numpy._typing._ufunc
- Occurs on Python 3.9 and 3.10
- Does not occur on Python 3.7 and 3.8
- Possibly related to Numpy and/or Sphinx versions
- See https://github.com/watertap-org/watertap/pull/1076#issuecomment-1690339095 for more information

```log
Exception raised:
    Traceback (most recent call last):
      File "C:\Miniconda\envs\watertap-dev\lib\doctest.py", line 1334, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 5, in <module>
        model = build_model()
      File "<doctest default[0]>", line 8, in build_model
        outputs = build_outputs(model, sweep_params)
      File "D:\a\watertap\watertap\watertap\examples\flowsheets\RO_with_energy_recovery\RO_with_energy_recovery.py", line 216, in set_operating_conditions
        m.fs.feed.properties.calculate_state(
      File "D:\a\watertap\watertap\watertap\property_models\NaCl_prop_pack.py", line 381, in calculate_state
        self.initialize(solver=solver, optarg=optarg, outlvl=outlvl)
      File "D:\a\watertap\watertap\watertap\property_models\NaCl_prop_pack.py", line 315, in initialize
        results = solve_indexed_blocks(opt, [self], tee=slc.tee)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\idaes\core\util\initialization.py", line 283, in solve_indexed_blocks
        results = solver.solve(tmp, **kwds)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\opt\base\solvers.py", line 597, in solve
        self._presolve(*args, **kwds)
      File "D:\a\watertap\watertap\watertap\core\plugins\solvers.py", line 106, in _presolve
        _, _, nlp = iscale.constraint_autoscale_large_jac(
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\idaes\core\util\scaling.py", line 695, in constraint_autoscale_large_jac
        nlp = PyomoNLP(m)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\interfaces\pyomo_nlp.py", line 108, in __init__
        super(PyomoNLP, self).__init__(nl_file)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\interfaces\ampl_nlp.py", line 56, in __init__
        self._asl = _asl.AmplInterface(self._nl_file)
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\asl.py", line 272, in __init__
        AmplInterface.ASLib, AmplInterface.interface_version = _LoadASLInterface(
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\contrib\pynumero\asl.py", line 32, in _LoadASLInterface
        array_1d_double = np.ctypeslib.ndpointer(
      File "C:\Miniconda\envs\watertap-dev\lib\site-packages\pyomo\common\dependencies.py", line 75, in __getattr__
        raise DeferredImportError(self._moduleunavailable_message())
    pyomo.common.errors.DeferredImportError: The numpy module (an optional Pyomo dependency) failed to import: ModuleNotFoundError: No module named 'numpy._typing._ufunc'
```

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary

- Pin Sphinx to v7.1.x
- Remove support for Python 3.7 as 3.8 is the minimum version supported by Sphinx 6+
  - Sphinx 7.2 (that seems to be correlated with the error occurring) requires Python 3.9+

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by bknueven — APPROVED** [review]
Happy to stop supporting 3.7.

Not related to this PR, but I did notice Pyomo tests against 3.11 now. We should probably start supporting Python 3.11 soon..

**Comment by lbianchi-lbl** [comment]
> Happy to stop supporting 3.7.
> 
> Not related to this PR, but I did notice Pyomo tests against 3.11 now. We should probably start supporting Python 3.11 soon..

Great point, I definitely agree (and IDAES also supports and tests against 3.11). I was planning on opening a separate PR once this is merged in.

**Review by avdudchenko — APPROVED** [review]
This looks good to me. I have no concerns dropping 3.7 support since we have been shipping WT with 3.8 I think since at least a year ago.

**Comment by bknueven** [comment]
@lbianchi-lbl it looks like we need to modify the commit rules for main to eliminate the test for Python 3.7 as "required" (and should probably make the Python 3.10 tests "required").

**Pull request merged**
