### PR TITLE
Remove more unused import statements

### PR DESCRIPTION
**Pull request by wigging**
## Fixes/Resolves:

More unused import statements were found. This pull request removes unnecessary imports.

## Summary/Motivation:

Several modules have unused imports which clutters up the code and causes warnings from linters.

## Changes proposed in this PR:
- Remove unused import statements

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
This should wait for #821 as it is similar but much smaller.

**Review by TimBartholomew — APPROVED** [review]
If it passes the tests, I think its fine.

**Comment by TimBartholomew** [comment]
Oh now there is a conflict...

**Review by ksbeattie — APPROVED** [review]
I have faith in the flake8!

**Comment by wigging** [comment]
Merge conflict is fixed. @lbianchi-lbl Let me know if anything else needs to be done for this pull request.

**Pull request merged**
