### PR TITLE
Infeasibility Explainer

### PR DESCRIPTION
**Pull request by bknueven**
## Fixes/Resolves: N/A
First pass at an infeasibility explanation tool. 

## Summary/Motivation:
Determining if and why a unit model or flowsheet is infeasible is a daunting task. This is an attempt at a tool to automate parts of that discovery.

## Changes proposed in this PR:
- [X] Add infeasibility explainer
- [ ] Add tests for infeasibility explainer
- [ ] Add documentation for infeasibility explainer

## Examples:

### Trivial Example
```IPython
In [1]: from pyomo.environ import *

In [2]: m = ConcreteModel()

In [3]: m.x = Var([1,2], bounds=(0,1))

In [4]: m.y = Var(bounds=(0, 1))

In [5]: m.c = Constraint(expr=m.x[1] * m.x[2] == -1)

In [6]: m.d = Constraint(expr=m.x[1] + m.y >= 1)

In [7]: from watertap.core.util.model_diagnostics.mis import compute_infeasibility_explanation

In [8]: compute_infeasibility_explanation(m)
...
Model unknown may be infeasible. A feasible solution was found with only the following variable bounds relaxed:
	ub of var x[1] by 4.46512621139961e-05
	lb of var x[2] by 0.9999553510105748
Another feasible solution was found with only the following variable bounds relaxed:
	lb of var x[1] by 0.7071067826864676
	ub of var x[2] by 0.4142135668713069
	ub of var y by 0.7071067851855212
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: c by 1.000000003759946
Computed Minimal Intractable System (MIS)!
Constraints / bounds in MIS:
	lb of var x[2]
	lb of var x[1]
	constraint: c
Constraints / bounds in guards for stability:

In [9]: 
```

### WaterTAP Example
Inside a unit model initialization routine, just prior to a failed solve:
```python
         from watertap.core.util.model_diagnostics.mis import compute_infeasibility_explanation
         compute_infeasibility_explanation(self)                                                                                                                                                                                                                            
```
Sample output:
```
Model fs.bed_stack may be infeasible. A feasible solution was found with only the following variable bounds relaxed:
	lb of var current_efficiency_x[0.0,0.0] by 0.7372378356850552
	lb of var current_efficiency_x[0.0,0.2] by 0.7026550308478341
	lb of var current_efficiency_x[0.0,0.4] by 0.6691120178271762
	lb of var current_efficiency_x[0.0,0.6] by 0.6365610163880433
	lb of var current_efficiency_x[0.0,0.8] by 0.6049573732183484
	lb of var current_efficiency_x[0.0,1.0] by 0.5742593008879877
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_dl_thickness[cem,anode_right,0.0,0.0] by 0.02160735897151261
	constraint: eq_dl_thickness[aem,cathode_left,0.0,0.0] by 0.02158975774768226
	constraint: diluate.properties[0.0,0.2].eq_conc_mol_phase_comp[Liq,Na+] by 0.03472168488274356
	constraint: diluate.properties[0.0,0.4].eq_conc_mol_phase_comp[Liq,Na+] by 0.033743977627278765
	constraint: diluate.properties[0.0,0.6].eq_conc_mol_phase_comp[Liq,Na+] by 0.03277728523118786
	constraint: diluate.properties[0.0,0.8].eq_conc_mol_phase_comp[Liq,Na+] by 0.03182116580259185
	constraint: diluate.properties[0.0,1.0].eq_conc_mol_phase_comp[Liq,Na+] by 0.030875193077162914
	constraint: concentrate.properties[0.0,0.2].eq_conc_mol_phase_comp[Liq,Na+] by 2.9426478209578598e-08
	constraint: concentrate.properties[0.0,0.4].eq_conc_mol_phase_comp[Liq,Na+] by 2.92896185497111e-08
	constraint: concentrate.properties[0.0,0.6].eq_conc_mol_phase_comp[Liq,Na+] by 2.914269188408894e-08
	constraint: concentrate.properties[0.0,0.8].eq_conc_mol_phase_comp[Liq,Na+] by 2.898556343832801e-08
	constraint: concentrate.properties[0.0,1.0].eq_conc_mol_phase_comp[Liq,Na+] by 2.8818124045758606e-08
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_dl_thickness[cem,anode_right,0.0,0.2] by 0.0030111918255875635
	constraint: eq_dl_thickness[aem,cathode_left,0.0,0.2] by 0.002987424089608927
	constraint: diluate.material_flow_linking_constraints[0.0,0.0,Liq,H2O] by 0.31161859826271004
	constraint: diluate.material_flow_linking_constraints[0.0,0.2,Liq,H2O] by 1.10088491092877e-08
	constraint: diluate.properties[0.0,0.0].eq_conc_mol_phase_comp[Liq,Na+] by 0.03571081886086052
	constraint: diluate.properties[0.0,0.2].eq_flow_mass_phase_comp[Liq,H2O] by 1.24479669355419e-08
	constraint: concentrate.material_flow_linking_constraints[0.0,0.0,Liq,H2O] by 1.0236707522852438e-08
	constraint: concentrate.properties[0.0,0.0].eq_conc_mol_phase_comp[Liq,Na+] by 8.320010882987096e-08
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_dl_thickness[cem,cathode_left,0.0,0.0] by 0.0756257597590177
	constraint: eq_dl_thickness[cem,cathode_left,0.0,0.2] by 0.0730815031749472
	constraint: eq_dl_thickness[cem,anode_right,0.0,0.4] by 0.0410518101204119
	constraint: eq_dl_thickness[cem,anode_right,0.0,0.6] by 0.020160616788550575
	constraint: eq_dl_thickness[cem,anode_right,0.0,0.8] by 0.019891761263729973
	constraint: eq_dl_thickness[cem,anode_right,0.0,1.0] by 0.01960706187225105
	constraint: eq_dl_thickness[aem,cathode_left,0.0,0.4] by 0.04103381614541684
	constraint: eq_dl_thickness[aem,cathode_left,0.0,0.6] by 0.020142557882098327
	constraint: eq_dl_thickness[aem,cathode_left,0.0,0.8] by 0.019873586714171578
	constraint: eq_dl_thickness[aem,cathode_left,0.0,1.0] by 0.019588772140875947
	constraint: eq_dl_thickness[aem,anode_right,0.0,0.0] by 0.07556415548734353
	constraint: eq_dl_thickness[aem,anode_right,0.0,0.2] by 0.07302080681189203
	constraint: diluate.properties[0.0,0.4].eq_conc_mol_phase_comp[Liq,Na+] by 7.806233050679046e-08
	constraint: diluate.properties[0.0,0.4].eq_conc_mol_phase_comp[Liq,Cl-] by 9.286061386563245e-08
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_dl_thickness[cem,cathode_left,0.0,0.4] by 0.07168541623331842
	constraint: eq_dl_thickness[cem,cathode_left,0.0,0.6] by 0.06921130844607552
	constraint: eq_dl_thickness[cem,cathode_left,0.0,0.8] by 0.06677722230127905
	constraint: eq_dl_thickness[cem,cathode_left,0.0,1.0] by 0.06437951094087464
	constraint: eq_dl_thickness[aem,anode_right,0.0,0.4] by 0.07162521177597515
	constraint: eq_dl_thickness[aem,anode_right,0.0,0.6] by 0.06915196442067169
	constraint: eq_dl_thickness[aem,anode_right,0.0,0.8] by 0.06671871036737628
	constraint: eq_dl_thickness[aem,anode_right,0.0,1.0] by 0.06432180430099106
	constraint: diluate.properties[0.0,0.0].eq_flow_mass_phase_comp[Liq,H2O] by 0.31984543158843115
	constraint: concentrate.material_flow_linking_constraints[0.0,0.2,Liq,H2O] by 5.9286015252579925e-08
	constraint: concentrate.properties[0.0,0.2].eq_dens_mass_phase[Liq] by 0.30668207879813836
	constraint: concentrate.properties[0.0,0.2].eq_flow_mass_phase_comp[Liq,H2O] by 5.930573996384278e-08
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_conc_polarization_ratio[aem,anode_right,0.0,0.2,Na+] by 0.040669586752677754
	constraint: diluate.material_flow_linking_constraints[0.0,0.0,Liq,Na+] by 0.8783201881406835
	constraint: concentrate.material_flow_linking_constraints[0.0,0.4,Liq,H2O] by 0.007799800414113325
	constraint: concentrate.material_flow_linking_constraints[0.0,0.6,Liq,H2O] by 0.0038819004695756837
	constraint: concentrate.properties[0.0,0.0].eq_dens_mass_phase[Liq] by 0.3123142778193591
	constraint: concentrate.properties[0.0,0.0].eq_flow_mass_phase_comp[Liq,H2O] by 2.025560361818027e-08
	constraint: concentrate.properties[0.0,0.4].eq_flow_mass_phase_comp[Liq,H2O] by 0.0076270122885626285
	constraint: concentrate.properties[0.0,0.6].eq_flow_mass_phase_comp[Liq,H2O] by 0.003838440372501425
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_conc_polarization_ratio[aem,cathode_left,0.0,0.2,Na+] by 1.079895698997256e-08
	constraint: eq_conc_polarization_ratio[aem,anode_right,0.0,0.0,Na+] by 0.41939778658415217
	constraint: eq_potential_nonohm_dl[cem,0.0,0.2] by 2.759288881399532e-08
	constraint: eq_potential_nonohm_dl[aem,0.0,0.2] by 2.75928888139951e-08
	constraint: eq_get_current_density[0.0,0.2] by 2.7592891663879247e-08
	constraint: diluate.material_flow_linking_constraints[0.0,0.2,Liq,Na+] by 0.0428685689831253
	constraint: diluate.material_flow_linking_constraints[0.0,0.4,Liq,H2O] by 8.41737955130646e-08
	constraint: diluate.material_flow_linking_constraints[0.0,0.6,Liq,H2O] by 7.144309177293345e-08
	constraint: diluate.material_balances[0.0,0.2,H2O] by 0.7620423557510609
	constraint: diluate.material_flow_dx_disc_eq[0.0,0.2,Liq,H2O] by 0.7620423557563031
	constraint: diluate.properties[0.0,0.2].eq_dens_mass_phase[Liq] by 1.768375763522983e-07
	constraint: diluate.properties[0.0,0.2].eq_flow_mass_phase_comp[Liq,Na+] by 2.080624394682309e-06
	constraint: diluate.properties[0.0,0.4].eq_flow_mass_phase_comp[Liq,H2O] by 0.00672208102719151
	constraint: diluate.properties[0.0,0.6].eq_flow_mass_phase_comp[Liq,H2O] by 5.837776469328908e-07
	lb of var potential_ohm_dl_x[aem,0.0,0.0] by 0.0049837758442454454
Another feasible solution was found with only the following inequality constraints, equality constraints, and/or variable bounds relaxed:
	constraint: eq_potential_nonohm_dl[cem,0.0,0.0] by 0.19336990837218815
	constraint: eq_potential_nonohm_dl[aem,0.0,0.0] by 0.1933698693425504
	constraint: eq_get_current_density[0.0,0.0] by 0.23814051659162785
	constraint: diluate.properties[0.0,0.2].eq_conc_mol_phase_comp[Liq,Cl-] by 8.318839098589663e-08
	constraint: diluate.properties[0.0,0.2].eq_conc_mass_phase_comp[Liq,Na+] by 1.269368323043906e-08
	constraint: diluate.properties[0.0,0.2].eq_mass_frac_phase_comp[Liq,Na+] by 1.2693683278060033e-08
	constraint: concentrate.material_flow_linking_constraints[0.0,0.0,Liq,Na+] by 1.186830609712056
	constraint: concentrate.material_flow_linking_constraints[0.0,0.2,Liq,Na+] by 0.00776271572676924
	constraint: concentrate.properties[0.0,0.2].eq_flow_mass_phase_comp[Liq,Na+] by 0.007788009800995113
Could not determine Minimal Intractable System
```
In this case, the first set of variable bounds reported above identified the issue with the model.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
Without looking into the details or code to do the comparison myself, how will this tool set itself apart from existing tools that @andrewlee94 (and others) have brought into IDAES?

**Comment by andrewlee94** [comment]
As a follow on to @adam-a-a's question, as this looks like it is something IDAES doesn't have yet, would the IDAES diagnostics toolbox be a better place for this?

**Comment by bknueven** [comment]
> As a follow on to @adam-a-a's question, as this looks like it is something IDAES doesn't have yet, would the IDAES diagnostics toolbox be a better place for this?

Could be. The tool is somewhat speculative in nature which is why I opened a draft PR here to get some initial feedback.

I developed it with @hunterbarber's feedback on the output to try to make it useful. A preliminary version was able to identify a problematic bound on a unit model he was working with.

**Comment by bknueven** [comment]
> Without looking into the details or code to do the comparison myself, how will this tool set itself apart from existing tools that @andrewlee94 (and others) have brought into IDAES?

I do not think something like this currently exists in IDAES, but its close cousins are the tools used to diagnose an infeasible solution from Ipopt, namely identifying variables at their bounds and the violated constraints. The attempts to do a more systematic analysis of a potentially infeasible problem.

**Comment by bknueven** [comment]
Closing -- this is a duplicate of Pyomo/pyomo#3172

**Pull request closed without merging**
