### PR TITLE
API for the WaterTAP UI

### PR DESCRIPTION
**Pull request by dangunter**
## Fixes/Addresses:

Issue #488 

## Summary/Motivation:

This PR provides an API framework for achieving this that will then be used for specific treatment train and unit models.

## Changes proposed in this PR:
- One module with the API
- Utility model for misc. things
- Unit tests

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
@TimBartholomew and @adam-a-a  this is mostly to reduce the size of the eventual PR , so a review with only nitpicks or even a rubber stamp would be fine. The API internals will no doubt get changed as I work through a real example. To see the external interface, look under `Technical Reference` -> `WaterTAP UI` in the generated docs.

**Comment by dangunter** [comment]
OK, this is passing except the RTD build, which is irrelevant since they are only warnings, and the codecov test which is irrelevant since it's codecov.

**Comment by dangunter** [comment]
@TimBartholomew et al., I'm just going to merge this

**Comment by aladshaw3** [comment]
@dangunter This was not passing the doc tests. How and why was this merged without all checks or approvals?

**Pull request merged**
