### PR TITLE
Experimental: Changing some bounds to 0

### LINKED ISSUE #510: Standarize "0" lower bounds in WaterTAP (esp. property packages)
In [some places](https://github.com/watertap-org/watertap/blob/b9a7d795c729818c1d0856c3f39fece8ec18ae4b/watertap/property_models/coagulation_prop_pack.py#L520) we use `1e-16`, in [other places](https://github.com/watertap-org/watertap/blob/b9a7d795c729818c1d0856c3f39fece8ec18ae4b/watertap/property_models/seawater_prop_pack.py#L989) we use `1e-8`.

Because Ipopt relaxes the bounds for the solve, often times the bound is internally relaxed anyways below zero (especially for bounds less than `1e-10`). Therefore, I think the best course of action would be to just change all these bounds to the value we mean -- `0`.

Since `ipopt-watertap` already does special handing of the bounds relaxation step, we could add additional logic to make sure the internally relaxed bounds do not cross zero. Then how close to zero you could get practically would be a function of the variable's scaling factor (which is probably nearly what is desired anyways).

### PR DESCRIPTION
**Pull request by bknueven**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by aladshaw3** [comment]
=========================== short test summary info ============================
FAILED watertap/core/tests/test_zero_order_diso.py::TestDISO::test_report - A...
FAILED watertap/core/tests/test_zero_order_sido.py::TestSIDO::test_report - A...
FAILED watertap/core/tests/test_zero_order_sido_reactive.py::TestSIDOR::test_report
FAILED watertap/examples/flowsheets/lsrro/tests/test_lsrro.py::TestLSRRO_3Stage::test_optimize
FAILED watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py::test_assert_electroneutrality_get_property
FAILED watertap/unit_models/mvc/components/tests/test_compressor.py::test_compressor
FAILED watertap/unit_models/zero_order/tests/test_CANDOP_zo.py::TestCANDOPZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_aeration_basin_zo.py::TestAerationBasinZO_no_default::test_report
FAILED watertap/unit_models/zero_order/tests/test_aeration_basin_zo.py::TestAerationBasinZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_air_flotation_zo.py::TestAirFloatationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_air_flotation_zo.py::TestAirFlotationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_anaerobic_digestion_oxidation_zo.py::TestAnaerobicDigestionOxidationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_anaerobic_digestion_oxidation_zo.py::TestAnaerobicDigestionOxidationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_anaerobic_mbr_mec_zo.py::TestAnaerobicMBRMECZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_backwash_solids_handling_zo.py::TestBackwashSolidsHandling_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_bio_active_filtration_zo.py::TestBioActiveFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_bio_active_filtration_zo.py::TestBioActiveFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_brine_concentrator_zo.py::TestBrineConcentratorZO_w_o_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_brine_concentrator_zo.py::Testbrine_concentratorZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py::TestCartridgeFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py::TestCartridgeFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_clarifier_zo.py::TestClarifierZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_clarifier_zo.py::TestClarifierZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_cofermentation_zo.py::TestCofermentationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_conventional_activated_sludge_zo.py::TestCASZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_cooling_tower_zo.py::TestCoolingTowerZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_dissolved_air_flotation_zo.py::TestAirDissolvedFloatationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_dissolved_air_flotation_zo.py::TestDissolvedAirFlotationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_dmbr_zo.py::TestDMBRZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_dual_media_filtration_zo.py::TestDualMediaFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_dual_media_filtration_zo.py::TestDualMediaFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_electrodialysis_reversal_zo.py::TestElectrodialysisReversalZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_evaporation_pond_zo.py::TestEvaporationPondZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_filter_press_zo.py::TestFilterPressZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_gac_zo.py::TestGACZO_w_o_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_gac_zo.py::TestGACZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_gas_sparged_membrane.py::TestGasSpargedMembraneZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_ion_exchange_zo.py::TestIonExchangeZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_ion_exchange_zo.py::TestIonExchangeZO_clinoptilolite::test_report
FAILED watertap/unit_models/zero_order/tests/test_iron_and_manganese_removal_zo.py::TestIronManganeseRemovalZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_mabr_zo.py::TestMABRZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_mbr_zo.py::TestMBRZOdefault::test_report
FAILED watertap/unit_models/zero_order/tests/test_mbr_zo.py::TestMBRZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_media_filtration_zo.py::TestMediaFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_media_filtration_zo.py::TestMediaFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_metab_zo.py::TestMetabZO_hydrogen::test_report
FAILED watertap/unit_models/zero_order/tests/test_metab_zo.py::TestMetabZO_methane::test_report
FAILED watertap/unit_models/zero_order/tests/test_microfiltration_zo.py::TestMicroFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_microfiltration_zo.py::TestMicroFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_microscreen_filtration_zo.py::TestMicroscreenFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_microscreen_filtration_zo.py::TestMicroscreenFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py::TestNFZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py::TestNFZO_non_default_subtype::test_report
FAILED watertap/unit_models/zero_order/tests/test_photothermal_membrane_zo.py::TestPhotothermalMembraneZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_primary_separator_zo.py::TestPrimarySeparatorZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_primary_separator_zo.py::TestPrimarySeparatorZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_screen_zo.py::TestScreenZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_secondary_treatment_wwtp_zo.py::TestSecondaryTreatmentWWTPZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_sedimentation_zo.py::TestSedimentationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_sedimentation_zo.py::TestSedimentationZO_phosphorus_capture_tss::test_report
FAILED watertap/unit_models/zero_order/tests/test_sedimentation_zo.py::TestSedimentationZO_phosphorus_capture_phosphates::test_report
FAILED watertap/unit_models/zero_order/tests/test_settling_pond_zo.py::TestSettlingPondZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_settling_pond_zo.py::TestSettlingPondZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_sludge_tank_zo.py::TestSludgeTankZO_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_sludge_tank_zo.py::TestSludgeTankZO_w_o_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_tri_media_filtration_zo.py::TestTriMediaFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_tri_media_filtration_zo.py::TestTriMediaFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_ultra_filtration_zo.py::TestUltraFiltrationZO::test_report
FAILED watertap/unit_models/zero_order/tests/test_ultra_filtration_zo.py::TestUltraFiltrationZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_vfa_recovery_zo.py::TestVFARecoveryZO_no_default::test_report
FAILED watertap/unit_models/zero_order/tests/test_vfa_recovery_zo.py::TestVFARecoveryZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_waiv_zo.py::TestWAIVZO_w_default_removal::test_report
FAILED watertap/unit_models/zero_order/tests/test_walnut_shell_filter_zo.py::TestWalnutShellFilterZO_w_default_removal::test_report

**Comment by aladshaw3** [comment]
It looks to me like this change is actually fine. All of the tests that fail only fail because the solutions have slightly changed. There were no issues with scaling, initialization, or finding an optimal solution (which are the most important pieces).

**Comment by bknueven** [comment]
Let's wait on #518 before merging this.

**Comment by bknueven** [comment]
Replaced by #570.

**Pull request closed without merging**
