### PR TITLE
Fix Pydantic 2 failures

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Fixes/Resolves:

Failures due to breaking changes in Pydantic 2 (used by `watertap.ui.fsapi`).

## Changes proposed in this PR:
- Add `<2` constraint to pydantic requirement

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
It actually looks like that Pydantic is pinned to 1.10 by `nbmake`, which is effectively "shielding" (or "tricking", depending on your point of view) us from the failures. Since the failures only appear when `nbmake` is not installed, i.e. a consequence of #1088, I'm closing this one and add the version constraint there.

**Comment by lbianchi-lbl** [comment]
**EDIT**: Pydantic 2.2 has *more* breaking changes, so I'm reopening this more targeted PR (as opposed to #1088) to be merged ASAP to resolve failures in e.g. #1038.

**Review by ksbeattie — APPROVED** [review]
LGTM

**Review by dangunter — APPROVED** [review]
LGTM

**Pull request merged**
