### PR TITLE
Adding OLI API

### PR DESCRIPTION
**Pull request by adam-a-a**
## Summary/Motivation:
Add OLI API with WaterTAP and OLI header.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adam-a-a** [comment]
@lbianchi-lbl I just noticed this (though it is not causing the failure) in the readthedocs check:

`/home/docs/checkouts/readthedocs.org/user_builds/watertap/envs/1056/lib/python3.7/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (1.19.2.4). Your version must be at least (2.14.2) but less than (4.0.0).
`

**Comment by TimBartholomew** [comment]
We will merge this in without extensive testing, later on we will refine it so that we test it with OLI credentials when triggered. 

All that needs to be done is running black and addressing the doc string failure for the documentation, but that will wait till @adam-a-a gets back from vacation.

**Comment by adam-a-a** [comment]
Notes from dev call: can probably skip coverage checks, but would need to resolve readthedocs error (something to do with indentation and the docstring in oli_api class). 

I can revisit this on the second week of August.

**Comment by adam-a-a** [comment]
@lbianchi-lbl I'll probably need to skip coverage checks for this PR.

**Comment by adam-a-a** [comment]
@lbianchi-lbl another issue now with the mac check. For some reason, when checking that my dictionary is as expected, all checks passed except for Mac, where some extra whitespace was detected causing the comparison to fail. I then tried using unittest to compare the dictionaries hoping that the differences between whitespace/spacing would be ignored, but that didn't work. Any thoughts?

**Review by OOAmusat — APPROVED** [review]
LGTM for a first pass.

**Comment by adam-a-a** [comment]
@veccp do you want to review? I just need one more approval to merge. You can also see how some preliminary testing was set up, which we'll probably have to get going for some of your additions.

**Comment by adam-a-a** [comment]
@lbianchi-lbl can you skip the codecov checks for this PR? We want to merge this in as a baseline so that new changes could be put up in subsequent PRs. As a reminder, a good chunk of this cannot be directly tested just yet without checks being able to access OLI functionality.

**Review by veccp — COMMENTED** [review]
Looks good

**Review by veccp — APPROVED** [review]

**Pull request merged**
