### PR TITLE
Parameter Estimation (parmest) Demo

### PR DESCRIPTION
**Pull request by savannahsakhai**
## Fixes/Resolves:
This is one item of the issue: Merge in Stakeholder Code Demos #1173.

## Summary/Motivation:
This adds the parameter estimation using parmest code demonstration given at the 2023 PSE+ stakeholder summit. 

## Changes proposed in this PR:
- adds a jupyter notebook for the code demo
- adds a csv for the necessary data from phreeqc

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by OOAmusat — APPROVED** [review]
My minor comment here would be maybe changing the format/structure of the input data, but that's not a reason to delay this.

Otherwise, LGTM.

**Comment by OOAmusat** [comment]
For a bit more context on why I commented on fixing the structure of the input data, this is what the data file looks like when I open it locally with Excel:

image

Cell A1 contains the number "55" which is not really part of the dataset. However, deleting the value and leaving the cell empty leads to failures in the notebook (at least on my end).

In the notebook, the data is pre-processed and the cell is ignored, so it is not a problem per-se. However, it is something we could (and probably should) easily fix.

**Comment by savannahsakhai** [comment]
> For a bit more context on why I commented on fixing the structure of the input data, this is what the data file looks like when I open it locally with Excel:
> 
> image
> Cell A1 contains the number "55" which is not really part of the dataset. However, deleting the value and leaving the cell empty leads to failures in the notebook (at least on my end).
> 
> In the notebook, the data is pre-processed and the cell is ignored, so it is not a problem per-se. However, it is something we could (and probably should) easily fix.

Thank you for adding more context to your original comment! I understand your concern now. If you look at the data provided in this PR, it should be corrected. I have updated the data set since the stakeholder summit. This new data was generated using phreeqc and the format should exclude that random placeholder number.

**Review by TimBartholomew — APPROVED** [review]

**Review by adam-a-a — APPROVED** [review]
Great job, @savannahsakhai! Will set to automerge

**Pull request merged**
