### PR TITLE
Expose model configuration options

### LINKED ISSUE #1084: Enable configuration of model options in UI
### Description

Fixes https://github.com/watertap-org/watertap-ui/issues/85

### Motivation

_No response_

### Possible Implementation

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dangunter**
Fixes #1084

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@dangunter, we put this (and the chain of 2 issues) on the Sept release board on the assumption that this will be ready in Sept.

**Comment by dangunter** [comment]
@MichaelPesce marking ready for review to simplify any contributions/testing. As mentioned in https://github.com/watertap-org/watertap-ui/pull/90 , the main to-do here is to show how the option value(s) are used in building/solving e.g. the nanofiltration flowsheet, and documenting how to use when wrapping new models.

**Comment by adam-a-a** [comment]
@dangunter - one thought about this functionality- selecting a specific configuration option could change whether certain variables should be available for the user to touch. One way to deal with this would be to be able to specify behind the scenese which vars would be "grayed out" and inaccessible with particular config options. It'd probably make sense to test this out starting simple with just an RO unit alone. Alternatively, we could look at this from the perspective of a given flowsheet, where you might want to toggle between predetermined variations of a given flowsheet. Personally, I think the former example would be better to start with.

**Comment by adam-a-a** [comment]
@dangunter @MichaelPesce I am trying to get back up to speed with state of the UI. I am behind at this point. 

Is this PR still relevant, or is this one already covered by other UI-related PRs? Please let me know so we can decide whether to review or close this one.

**Comment by adam-a-a** [comment]
This PR was superseded by #1152

**Pull request closed without merging**
