### PR TITLE
OARO remove spiral-wound ModuleType

### PR DESCRIPTION
**Pull request by zacharybinger**
## Fixes/Resolves:
#1380 

## Summary/Motivation:
Implementation of OARO with a spiral-wound module is more complex than the initial implementation represented. Enabling spiral-wound operation of OARO would likely require another PR with more creative/extensive changes that I don't think are possible with our current capabilities. More precisely spiral-wound OARO would require a 2D model.

## Changes proposed in this PR:
- Removing ModuleType.spiral_wound support for OARO models

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by MarcusHolly — APPROVED** [review]
LGTM

**Comment by adam-a-a** [comment]
>  Enabling spiral-wound operation of OARO would likely require another PR with more creative/extensive changes that I don't think are possible with our current capabilities

Just want to clarify that the underlying _capabilities_ are there (e.g., IDAES has at least one 2d model that I can recall off the top of my head)--it is just that we haven't implemented any 2d models in WaterTAP thus far. Although such an effort would require a lot of time and effort, I just want to make sure that anyone reading through this PR understands that such a model is possible in WaterTAP and would be facilitated by some of the building blocks in IDAES.

**Review by adam-a-a — CHANGES_REQUESTED** [review]
LGTM- the only necessary changes are updating the documentation for OARO 0D and 1D, wherever spiral-wound modules are mentioned.

**Comment by ElmiraShamlou** [comment]
@zacharybinger @adam-a-a How about keeping the spiral wound option for the OARO 0D model instead of fully removing it? For velocity calculations in the permeate channel, we can redefine the cross-sectional area as follows:

Velocity (permeate channel) = Qavg / (Porosity * (Module Length / 2) * Channel Height)
where:
Module Length: Length of the module (used instead of width to reflect the perpendicular flow direction)
Division by 2: Accounts for the effects of baffles in the permeate channel

**Comment by adam-a-a** [comment]
> @zacharybinger @adam-a-a How about keeping the spiral wound option for the OARO 0D model instead of fully removing it? For velocity calculations in the permeate channel, we can redefine the cross-sectional area as follows:
> 
> Velocity (permeate channel) = Qavg / (Porosity * (Module Length / 2) * Channel Height) where: Module Length: Length of the module (used instead of width to reflect the perpendicular flow direction) Division by 2: Accounts for the effects of baffles in the permeate channel

Hmm.. maybe that _could_ work. Does anyone know if we have any peer-reviewed literature on spiral wound OARO performance to test against?

**Comment by zacharybinger** [comment]
> .. maybe that _could_ work. Does anyone know if we have any peer-reviewed literature on spiral wound OARO performance to test against?

Not to my knowledge, nor in the quick literature search I just did

**Comment by adam-a-a** [comment]
@zacharybinger - just a reminder that this PR should be good to go soon--just waiting on the corresponding updates to the documentation to reflect removal of SW module type from OARO. We can revisit @ElmiraShamlou 's suggestion via a subsequent issue/PR as needed.

**Comment by zacharybinger** [comment]
@adam-a-a Ok, once these checks pass it should be good to go then. I removed any mention of spiral-wound from the docs, there were only a few lines

**Review by adam-a-a — APPROVED** [review]
LGTM

**Pull request merged**
