### PR TITLE
Add model to solve function in UI

### PR DESCRIPTION
**Pull request by avdudchenko**
## Fixes/Resolves:
Currently, UI passes the flowsheet (m.fs) into the solve function used by the UI, but to be consistent with rest of watertap usage/IDAES usage, we should be passing in the model it self (m) into the solve function. This updates the fast api to pass the model in, and rest of uis to handle the new behavior. 

(replace this with the issue # fixed or resolved, if no issue exists then a brief statement of what this PR does)

## Summary/Motivation:
- include model for users to solve in ui solve function. 

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by MichaelPesce — APPROVED** [review]

**Review by adam-a-a — COMMENTED** [review]
My only issue with this is a petty one--we are maintaining the `flowsheet` arg when it should now be `model`, based on your changes, technically.

**Comment by avdudchenko** [comment]
> My only issue with this is a petty one--we are maintaining the `flowsheet` arg when it should now be `model`, based on your changes, technically.

I left it as that for now to make it clear that the change is happening, but over time we should switch it over to "model", not sure it makes sense @MichaelPesce and @dangunter  and if we should just update flowsheet to be model through out...

**Comment by avdudchenko** [comment]
@adam-a-a @MichaelPesce @dangunter I updated the PR so it now uses model through out.

**Comment by adam-a-a** [comment]
@dangunter from discussions during last dev call, I recall that you wanted to weigh in here. @avdudchenko has gone ahead and revised the `flowsheet` arg as `model`, matching up with his new changes. However, you may want to see how this channels through under the hood.

**Comment by ksbeattie** [comment]
@avdudchenko, @adam-a-a I believe we decided to hold on this for the moment.

**Comment by avdudchenko** [comment]
We should complete merging this - in effect the way we use UI right now with flowsheet vs model is broken. can we merge this in? Before more UI's are added into WT?) @dangunter @MichaelPesce @adam-a-a

**Comment by lbianchi-lbl** [comment]
> We should complete merging this - in effect the way we use UI right now with flowsheet vs model is broken. can we merge this in? Before more UI's are added into WT?) @dangunter @MichaelPesce @adam-a-a

@avdudchenko Apologies for not providing more context. After a bit of a back and forth in the dev call, the consensus seems to be:

- Conceptually:
  - The general question of "should `watertap.ui.fsapi` be based around the `ConcreteModel` instance or the `FlowsheetBlock` instance?" might have some merit
  - However, both have their pros and cons, so the opinion seems to be that `ConcreteModel` is not the obviously "better" choice
- Concretely:
  - This would be a disruptive change that would require a considerable amount of effort, and the maintainers of this part of the WaterTAP codebase don't have the bandwidth to deal with this for the foreseeable future
  - The need for being able to access the `ConcreteModel` instance has not been a requirement for most UI modules until now
  - There is a straightforward workaround that only relies on documented/public Pyomo APIs and is therefore a valid choice when this need does exist

The workaround is calling `fs.model()`, which will return the `ConcreteModel` instance from any `Block` no matter its position in the block tree.

Given the above, our decision was to close this PR as not planned. Does it make sense? If you get a chance of trying out the `fs.model()` workaround and you think it's a reasonable solution, we could think of adding some documentation (perhaps a short "How to" guide) for future reference.

**Pull request closed without merging**
