### PR TITLE
Change small positive bounds to 0

### LINKED ISSUE #510: Standarize "0" lower bounds in WaterTAP (esp. property packages)
In [some places](https://github.com/watertap-org/watertap/blob/b9a7d795c729818c1d0856c3f39fece8ec18ae4b/watertap/property_models/coagulation_prop_pack.py#L520) we use `1e-16`, in [other places](https://github.com/watertap-org/watertap/blob/b9a7d795c729818c1d0856c3f39fece8ec18ae4b/watertap/property_models/seawater_prop_pack.py#L989) we use `1e-8`.

Because Ipopt relaxes the bounds for the solve, often times the bound is internally relaxed anyways below zero (especially for bounds less than `1e-10`). Therefore, I think the best course of action would be to just change all these bounds to the value we mean -- `0`.

Since `ipopt-watertap` already does special handing of the bounds relaxation step, we could add additional logic to make sure the internally relaxed bounds do not cross zero. Then how close to zero you could get practically would be a function of the variable's scaling factor (which is probably nearly what is desired anyways).

### PR DESCRIPTION
**Pull request by bknueven**
## Fixes/Resolves:
Replaces #511, Fixes #510

## Summary/Motivation:
See #510

## Changes proposed in this PR:
- Change all small lower bounds in WaterTAP to 0
- Update affected tests, namely complete condenser and LSRRO

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by aladshaw3** [comment]
@bknueven @TimBartholomew 

The 1 test that is failing is: 'watertap/examples/flowsheets/lsrro/tests/test_lssro_multi_sweep.py F'

Oddly, it is only failing on the linux build for python 3.7. The values expected in that test are so far off that it leads me to believe that there is some numerical stability problem with the lssro model. It is reporting a lot of issues with initialization and ultimately states that it reaches and infeasible point during the final solve. 

The associated initialization issues are in the RO units. These may need some better scaling and/or initialization.

**Comment by bknueven** [comment]
> The 1 test that is failing is: 'watertap/examples/flowsheets/lsrro/tests/test_lssro_multi_sweep.py F'
> 
> Oddly, it is only failing on the linux build for python 3.7. The values expected in that test are so far off that it leads me to believe that there is some numerical stability problem with the lssro model. It is reporting a lot of issues with initialization and ultimately states that it reaches and infeasible point during the final solve.

This is to be expected. There's some magic I wrote for the LSRRO tests which distribute its jobs between the GHA runners, so as not to bog down our testing procedure.

The LSRRO flowsheets are somewhat sensitive to changes in the underlying models and properties.

**Comment by bknueven** [comment]
I got a chance to look more closely at the failing LSRRO test. I'm not particularly concerned. A few RO unit models have trouble initializing at the beginning of the initialize run, but they are initialize cleanly by the first backwards pass.

Further, the obtained LCOW with this PR is slightly lower than on main (0.2814 vs 0.2851). It also looks to me like the solution with this PR (Obtained) is higher quality than that in the baseline (Expected). @adam-a-a, mind having a look?

```
E             Max relative difference: 2216456.484912721
E             Index                                       | Obtained     | Expected                    
E             LCOW                                        | 0.2814249    | 0.2850692 ± 2.9e-03         
E             LCOW wrt Feed Flow                          | 0.2532824    | 0.2565622 ± 2.6e-03         
E             SEC                                         | 1.427921     | 1.7709669999999995 ± 1.8e-02
E             SEC wrt Feed                                | 1.285129     | 1.59387 ± 1.6e-02           
E             Final Permeate Concentration (ppm)          | 91.08149     | 126.8609 ± 1.3e+00          
E             Pump Work In (kW)                           | 4.751027     | 6.068201 ± 6.1e-02          
E             Pump Work Recovered (kW)                    | -0.1245618   | -0.3302691 ± 3.3e-03        
E             Net Pump Work In (kW)                       | 4.626465     | 5.737932 ± 5.7e-02          
E             Energy Recovery (%)                         | 2.621787     | 5.44262 ± 5.4e-02           
E             Total Membrane Area                         | 151.9797     | 119.5426 ± 1.2e+00          
E             Total Capex LCOW                            | 0.1175371    | 0.1074293999999999 ± 1.1e-03
E             Total Opex LCOW                             | 0.1638877    | 0.1776398 ± 1.8e-03         
E             Primary Pump Capex LCOW                     | 0.03537043   | 0.03754126 ± 3.8e-04        
E             Booster Pump Capex LCOW                     | 0.002138422  | 0.0002606613 ± 2.6e-06      
E             ERD Capex LCOW                              | 0.002144982  | 0.001560658 ± 1.6e-05       
E             Membrane Capex LCOW                         | 0.01911474   | 0.01435211 ± 1.4e-04        
E             Indirect Capex LCOW                         | 0.05876857   | 0.05371468 ± 5.4e-04        
E             Electricity LCOW                            | 0.0999545    | 0.1238828 ± 1.2e-03         
E             Membrane Replacement LCOW                   | 0.0286721    | 0.02152816 ± 2.2e-04        
E             Chem-labor-maintenance LCOW                 | 0.03526114   | 0.03222881 ± 3.2e-04        
E             Pumping Energy Agg LCOW                     | 0.2030545    | 0.2262255 ± 2.3e-03         
E             Membrane Agg LCOW                           | 0.07837042   | 0.05884363 ± 5.9e-04        
E             Feed Pressure (bar)-Stage 1                 | 32.12115     | 46.18282 ± 4.6e-01          
E             Feed Pressure (bar)-Stage 2                 | 38.77409     | 10.06943 ± 1.0e-01          
E             Feed Pressure (bar)-Stage 3                 | 36.57932     | 10.00001 ± 1.0e-01          
E             Feed Pressure (bar)-Stage 4                 | 26.57934     | 10.00001 ± 1.0e-01          
E             Feed Pressure (bar)-Stage 5                 | 16.57946     | 10.0 ± 1.0e-01              
E             Membrane Area-Stage 1                       | 135.6472     | 115.4247 ± 1.2e+00          
E             Membrane Area-Stage 2                       | 13.33255     | 1.117884 ± 1.1e-02          
E             Observed Rejection (%)-Stage 2              | 83.69651     | 9.645992 ± 9.6e-02          
E             Observed Rejection (%)-Stage 3              | 72.23914     | 19.912470000000003 ± 2.0e-01
E             Observed Rejection (%)-Stage 4              | 49.93694     | 19.91189 ± 2.0e-01          
E             Observed Rejection (%)-Stage 5              | 35.735       | 19.89306 ± 2.0e-01          
E             Observed Salt Passage (%)-Stage 1           | 1.822225     | 2.39755 ± 2.4e-02           
E             Observed Salt Passage (%)-Stage 2           | 16.30349     | 90.35401 ± 9.0e-01          
E             Observed Salt Passage (%)-Stage 3           | 27.76086     | 80.08753 ± 8.0e-01          
E             Observed Salt Passage (%)-Stage 4           | 50.06306     | 80.08811 ± 8.0e-01          
E             Observed Salt Passage (%)-Stage 5           | 64.265       | 80.10694000000001 ± 8.0e-01 
E             Mass Salt Passage (%)-Stage 1               | 1.51223      | 2.143023 ± 2.1e-02          
E             Mass Salt Passage (%)-Stage 2               | 7.374503     | 5.769549 ± 5.8e-02          
E             Mass Salt Passage (%)-Stage 3               | 0.5998731    | 0.8008894 ± 8.0e-03         
E             Mass Salt Passage (%)-Stage 4               | 0.5006362    | 0.800892 ± 8.0e-03          
E             Mass Salt Passage (%)-Stage 5               | 0.6426599    | 0.8010803000000001 ± 8.0e-03
E             Volumetric Module Recovery Rate (%)-Stage 1 | 82.9881      | 89.38387 ± 8.9e-01          
E             Volumetric Module Recovery Rate (%)-Stage 2 | 45.23266     | 6.385493 ± 6.4e-02          
E             Volumetric Module Recovery Rate (%)-Stage 3 | 2.160859     | 1.000018 ± 1.0e-02          
E             Mass Water Module Recovery Rate (%)-Stage 1 | 83.08723     | 89.49634 ± 8.9e-01          
E             Mass Water Module Recovery Rate (%)-Stage 2 | 45.51623     | 6.394251000000001 ± 6.4e-02 
E             Mass Water Module Recovery Rate (%)-Stage 3 | 2.181758     | 1.00284 ± 1.0e-02           
E             Volumetric Stage Recovery Rate (%)-Stage 2  | 45.78002     | 6.446448999999999 ± 6.4e-02 
E             Volumetric Stage Recovery Rate (%)-Stage 3  | 2.18242      | 1.010117 ± 1.0e-02          
E             Mass Water Stage Recovery Rate (%)-Stage 2  | 46.06936     | 6.455463 ± 6.5e-02          
E             Mass Water Stage Recovery Rate (%)-Stage 3  | 2.203681     | 1.012998 ± 1.0e-02          
E             B-Value (LMH)-Stage 2                       | 2.647485     | 171.7711 ± 1.7e+00          
E             B-Value (LMH)-Stage 3                       | 3.023872     | 14.18364 ± 1.4e-01          
E             B-Value (LMH)-Stage 4                       | 3.746363     | 14.18273 ± 1.4e-01          
E             B-Value (LMH)-Stage 5                       | 6.271107     | 14.06279 ± 1.4e-01          
E             Average Water Flux (LMH)-Stage 1            | 23.76555     | 27.929040000000004 ± 2.8e-01
E             Average Water Flux (LMH)-Stage 2            | 22.67452     | 21.84846 ± 2.2e-01          
E             Average Water Flux (LMH)-Stage 3            | 7.974423     | 3.621918 ± 3.6e-02          
E             Average NaCl Flux (GMH)-Stage 1             | 2.164799     | 3.543554 ± 3.5e-02          
E             Average NaCl Flux (GMH)-Stage 2             | 106.3762     | 971.3249 ± 9.7e+00          
E             Average NaCl Flux (GMH)-Stage 3             | 107.3974     | 143.1775 ± 1.4e+00          
E             Average NaCl Flux (GMH)-Stage 4             | 89.66639     | 143.169 ± 1.4e+00           
E             Average NaCl Flux (GMH)-Stage 5             | 114.5273     | 142.0558 ± 1.4e+00          
E             Pressure Drop (bar)-Stage 1                 | 2.82822      | 5.929711 ± 5.9e-02          
E             Pressure Drop (bar)-Stage 2                 | 2.194766     | 0.06942993 ± 6.9e-04        
E             Pressure Drop (bar)-Stage 3                 | 9.999988     | 0.01393627 ± 1.4e-04        
E             Pressure Drop (bar)-Stage 4                 | 9.999892     | 0.01393764 ± 1.4e-04        
E             Inlet Reynolds Number-Stage 1               | 250.7381     | 411.1274 ± 4.1e+00          
E             Inlet Reynolds Number-Stage 2               | 216.4632     | 88.2487 ± 8.8e-01           
E             Inlet Reynolds Number-Stage 3               | 732.4927     | 41.760670000000005 ± 4.2e-01
E             Inlet Reynolds Number-Stage 4               | 725.2256     | 41.76046 ± 4.2e-01          
E             Outlet Reynolds Number-Stage 2              | 115.7692     | 82.5827 ± 8.3e-01           
E             Outlet Reynolds Number-Stage 3              | 716.0276     | 41.33832 ± 4.1e-01          
E             Outlet Reynolds Number-Stage 4              | 717.7681     | 41.33812 ± 4.1e-01          
E             Inlet Crossflow Velocity-Stage 1            | 0.2340848    | 0.3839791999999999 ± 3.8e-03
E             Inlet Crossflow Velocity-Stage 2            | 0.2085871    | 0.08712453 ± 8.7e-04        
E             Inlet Crossflow Velocity-Stage 3            | 0.7229238    | 0.0412394 ± 4.1e-04         
E             Inlet Crossflow Velocity-Stage 4            | 0.7162528    | 0.04123929 ± 4.1e-04        
E             Outlet Crossflow Velocity-Stage 1           | 0.03983738   | 0.0408097 ± 4.1e-04         
E             Outlet Crossflow Velocity-Stage 2           | 0.1142887    | 0.08156126 ± 8.2e-04        
E             Outlet Crossflow Velocity-Stage 3           | 0.707312     | 0.04082702 ± 4.1e-04        
E             Outlet Crossflow Velocity-Stage 4           | 0.7090923    | 0.04082691 ± 4.1e-04        
E             Primary Pump SEC-Stage 1                    | 1.280161     | 1.85883 ± 1.9e-02           
E             Primary Pump SEC-Stage 2                    | 0.07201113   | 3.248929e-08 ± 1.0e-07      
E             Primary Pump SEC-Stage 4                    | 2.023478e-08 | 5.798005e-05 ± 5.8e-07      
E             Primary Pump SEC-Stage 5                    | 3.315552e-08 | 5.797701e-05 ± 5.8e-07      
E             Booster Pump SEC-Stage 2                    | 0.1081645    | 0.01282328 ± 1.3e-04        
E             Booster Pump SEC-Stage 3                    | 0.003471023  | 0.0003807319999999 ± 3.8e-06
E             Booster Pump SEC-Stage 4                    | 0.001495096  | 0.0003777739 ± 3.8e-06      
E             Booster Pump SEC-Stage 5                    | 0.001063986  | 0.0003739961 ± 3.7e-06      
E             ERD SEC-Stage 1                             | -5.36975e-08 | -0.07975468 ± 8.0e-04       
E             ERD SEC-Stage 5                             | -0.03844495  | -0.02218023 ± 2.2e-04       
E             Net SEC-Stage 1                             | 1.280161     | 1.779075 ± 1.8e-02          
E             Net SEC-Stage 2                             | 0.1801756    | 0.01282332 ± 1.3e-04        
E             Net SEC-Stage 3                             | 0.003471038  | 0.0003807833999999 ± 3.8e-06
E             Net SEC-Stage 4                             | 0.001495116  | 0.000435754 ± 4.4e-06       
E             Net SEC-Stage 5                             | -0.03738094  | -0.02174826 ± 2.2e-04
```

**Review by aladshaw3 — APPROVED** [review]
LGTM. 

Should also definitely get reviewed and approved by @adam-a-a and/or @TimBartholomew to make sure that the changes in the expected results for lssro are reasonable.

**Comment by adam-a-a** [comment]
> 

I have to see what case this corresponds to. It looks like a 5-stage, but not clear on the recovery and feed salinity. Whatever the case may be, it seems like this system is oversized (too many stages) for what is needed, given the feed salinity and recovery rate. That is relieving because then that means this set of results doesn't correspond to key results in the paper. At most, we might update our SI data in csv files. 

@bknueven Is that in line with your thinking?

EDIT 1: It seems that the 5-stage example posted above corresponds to 5 g/l feed, 90% recovery, which likely can get away with less stages. My assumption is that at the cost-optimal number of stages, the variation between expected results and actual results after min bound modifications should be minimal, while said variation will be higher for stage configurations that are not optimal.

EDIT 2: Looking more closely at the LSRRO results, I see that the cost-optimal setup corresponds to a 1-stage system, and from eyeballing the first set of key results (e.g., LCOW, SEC, etc.), it appears that there is a negligible difference between expected and actual results, so my previous assumption is likely correct.

**Review by adam-a-a — APPROVED** [review]
LGTM- despite differences observed for LSSRO tests, we need to consider that if the optimization run deviates significantly from the cost-optimal number of stages, we can expect dramatic deviations in results due to subtle adjustments to input values and bounds. That was the case for the more questionable set of LSRRO results, so I think we should be OK.

**Comment by bknueven** [comment]
> LGTM- despite differences observed for LSSRO tests, we need to consider that if the optimization run deviates significantly from the cost-optimal number of stages, we can expect dramatic deviations in results due to subtle adjustments to input values and bounds. That was the case for the more questionable set of LSRRO results, so I think we should be OK.

Right -- I think when there's too many stages, the problem has many, many, local minima. Further, this PR actually helps Ipopt in this case find a more cost-optimal and less trivial solution, looking at e.g., the later stage pressures and rejection.

**Pull request merged**
