### PR TITLE
Add reference text and citation file

### PR DESCRIPTION
**Pull request by wigging**
## Fixes/Resolves:

Resolves issue #832 by providing reference text for the project.

## Summary/Motivation:

Adds a citation file which is supported by GitHub to reference software. Text that can be used to reference the WaterTAP project is also added to the README and documentation.

## Changes proposed in this PR:
- Add a citation file
- Add reference text to README and documentation

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by wigging** [comment]
See [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) for an overview of CITATION files on GitHub.

**Review by adam-a-a — APPROVED** [review]
LGTM!

**Review by lbianchi-lbl — CHANGES_REQUESTED** [review]
I think this is a fine idea, but I'm concerned about keeping the list of authors up-to-date in the long run if individual names are listed. For the same reason, I also see the fact that the same list is repeated twice in non-machine-readable files (in `README.md` and `docs/index.rst`), which would have to be manually synced to the `CITATION.cff`.

As a "cheap" way to bypass both problems, if there are no strong reasons or preferences against it, I suggest we consider using a more general `WaterTAP contributors` (using the appropriate schema for the format) instead of listing the names.

**Comment by wigging** [comment]
@lbianchi-lbl See latest commit.

**Review by lbianchi-lbl — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
